import type { ComponentDef, FlowDef, LearnStep, VehicleDef, WalkZone } from '../data/types'
import type { CarLayout } from '../models/carLayout'
import { carSystems, carLayers, carStart } from './common'

/*
 * Representative BMW 530i (G30, 2017–2023): B48 2.0 L turbocharged inline-4 with direct injection,
 * 8-speed Steptronic automatic, rear-wheel drive (xDrive all-wheel drive optional).
 * Schematic layout at real overall dimensions, not CAD.
 */
const L: CarLayout = {
  paint: '#1d3a5c',
  width: 1.868, wheelbase: 2.975, track: 1.6, wheelR: 0.335, tireW: 0.245,
  front: 2.34, rear: -2.6, belt: 1.0, roof: 1.47,
  profile: [[2.28, 0.3], [2.34, 0.52], [2.31, 0.71], [2.05, 0.8], [0.86, 0.97], [-0.05, 1.43], [-0.28, 1.47], [-1.15, 1.44], [-1.9, 1.15], [-2.5, 1.08], [-2.6, 0.95], [-2.59, 0.4], [-2.5, 0.3]],
  sill: 0.3, archR: 0.4,
  window: [[0.72, 1.0], [-0.03, 1.39], [-1.12, 1.4], [-1.78, 1.1], [-1.62, 1.0]],
  windshield: [[0.86, 0.98, 0], [-0.03, 1.42, 0]],
  rearGlass: [[-1.88, 1.16, 0], [-1.2, 1.43, 0]],
  hood: { x0: 2.0, x1: 0.92, y0: 0.81, y1: 0.965 },
  tailgate: { hinge: [-1.92, 1.15, 0], to: [-2.55, 1.07, 0] },
  door: { x0: -0.6, x1: 0.55, y0: 0.36, y1: 1.0 },
  frame: false,
  engine: { x: 1.1, y: 0.6, len: 0.6, bore: 0.082, crankY: 0.42, cyl: 4 },
  turbo: [1.0, 0.6, -0.36],
  intercooler: { pos: [1.1, 0.7, 0.31], size: [0.46, 0.1, 0.13], label: 'water' },
  airbox: [1.75, 0.76, 0.34],
  radiator: { x: 2.12, y: 0.52, h: 0.36, w: 0.8 },
  condenser: 2.19,
  battery: [-2.15, 0.56, -0.55],
  alternator: [1.45, 0.5, 0.2],
  starter: [0.84, 0.38, 0.22],
  waterPump: [1.44, 0.46, 0],
  ecu: [1.72, 0.64, 0.56],
  hpPump: [0.85, 0.78, 0.12],
  fuelFilter: [-0.78, 0.34, 0.5],
  absUnit: [1.62, 0.66, -0.55],
  booster: [0.74, 0.78, 0.42],
  acCompressor: [1.46, 0.36, -0.22],
  hvac: [0.42, 0.72, 0],
  gearbox: { x0: 0.78, x1: -0.12, y: 0.4, r: 0.18 },
  rearDiff: [-1.4875, 0.335, 0],
  tank: { pos: [-1.0, 0.33, 0], size: [0.6, 0.22, 1.1], saddle: true },
  exhaust: [[1.0, 0.55, -0.38], [0.95, 0.42, -0.38], [0.85, 0.28, -0.3], [0.5, 0.22, -0.2], [-0.4, 0.21, -0.16], [-1.2, 0.22, -0.2], [-1.85, 0.26, -0.3], [-2.25, 0.3, -0.42], [-2.58, 0.3, -0.48]],
  cat: { x0: 0.94, x1: 0.62 },
  muffler: { pos: [-2.28, 0.3, 0], len: 0.62, r: 0.12, transverse: true },
  tailpipe: [-2.58, 0.3, -0.5],
  seatsFront: -0.35, seatsRear: -1.3, seatY: 0.48, floorY: 0.27,
  steeringWheel: [0.18, 0.92, 0.38],
  rack: [1.32, 0.36, 0],
  pedals: [0.58, 0.56, 0.38],
  dash: 0.42,
  rearAxle: 'multilink',
  caliper: '#2b63d6',
  lights: { head: [2.25, 0.73, 0.68], tail: [-2.56, 0.96, 0.72] },
  trunkBattery: true,
  petrol: true,
}

const cyl = [1.2935, 1.1645, 1.0355, 0.9065]
const deck = 0.661

const flows: FlowDef[] = [
  // FUEL
  { id: 'fuel-supply', kind: 'fuel', label: 'Бак → магистраль', points: [[-0.85, 0.36, 0.33], [-0.6, 0.2, 0.45], [0.2, 0.2, 0.46], [0.6, 0.24, 0.44], [0.8, 0.5, 0.36], [0.85, 0.74, 0.16]], speed: 0.8 },
  { id: 'fuel-hp', kind: 'fuel', label: 'ТНВД → рампа', points: [[0.85, 0.74, 0.16], [0.9, 0.71, 0.16], [1.33, 0.71, 0.16]], speed: 1.6, density: 34 },
  ...cyl.map((x, i) => ({ id: `fuel-inj-${i}`, kind: 'fuel' as const, label: `Форсунка ${i + 1}`, points: [[x, 0.71, 0.16], [x, 0.68, 0.12], [x, deck - 0.02, 0.03]] as [number, number, number][], speed: 1.8, density: 40 })),
  { id: 'fuel-evap', kind: 'fuel', label: 'Пары бензина → адсорбер', points: [[-1.0, 0.45, 0], [-0.4, 0.24, 0.55], [0.6, 0.25, 0.6], [1.6, 0.5, 0.6]], speed: 0.4, density: 8 },
  // AIR
  { id: 'air-intake', kind: 'air', label: 'Забор воздуха', points: [[2.2, 0.72, 0.4], [1.95, 0.76, 0.36], [1.85, 0.76, 0.34]] },
  { id: 'air-turbo', kind: 'air', label: 'Фильтр → компрессор', points: [[1.6, 0.78, 0.2], [1.35, 0.8, -0.1], [1.1, 0.7, -0.3], [1.02, 0.64, -0.36]] },
  { id: 'air-boost', kind: 'air', label: 'Компрессор → охладитель наддува', points: [[1.0, 0.6, -0.44], [1.3, 0.5, -0.44], [1.5, 0.55, 0.0], [1.42, 0.68, 0.31], [1.33, 0.7, 0.31]], speed: 1.4 },
  { id: 'air-manifold', kind: 'air', label: 'Впускной коллектор', points: [[1.33, 0.7, 0.31], [1.1, 0.7, 0.31], [0.87, 0.7, 0.31]], speed: 1.4 },
  ...cyl.map((x, i) => ({ id: `air-port-${i}`, kind: 'air' as const, label: 'Впуск', points: [[x, 0.7, 0.27], [x, 0.69, 0.12], [x, deck - 0.01, 0.03]] as [number, number, number][], speed: 1.2, density: 30 })),
  { id: 'air-cabin', kind: 'air', label: 'Воздух в салон', points: [[0.42, 0.78, 0], [0.32, 0.9, 0.3], [0.0, 0.95, 0.4], [-0.8, 1.1, 0.2], [-1.4, 1.1, 0]], speed: 0.6, density: 10 },
  // EXHAUST
  ...cyl.map((x, i) => ({ id: `exh-port-${i}`, kind: 'exhaust' as const, label: 'Выпуск', points: [[x, deck - 0.01, -0.03], [x, deck, -0.15], [x, deck, -0.27]] as [number, number, number][], speed: 1.3, density: 30 })),
  { id: 'exh-manifold', kind: 'exhaust', label: 'Коллектор → турбина', points: [[0.88, deck, -0.27], [0.98, deck - 0.02, -0.3], [1.0, 0.62, -0.34]], speed: 1.3 },
  { id: 'exh-main', kind: 'exhaust', label: 'Турбина → катализатор → глушитель', points: [[1.0, 0.55, -0.38], [0.95, 0.42, -0.38], [0.85, 0.28, -0.3], [0.5, 0.22, -0.2], [-0.4, 0.21, -0.16], [-1.2, 0.22, -0.2], [-1.85, 0.26, -0.3], [-2.25, 0.3, -0.42], [-2.72, 0.3, -0.5]], speed: 1.2 },
  // OIL
  { id: 'oil-pump', kind: 'oil', label: 'Поддон → насос → фильтр', points: [[1.1, 0.27, 0], [1.33, 0.29, 0], [1.38, 0.38, 0.2], [1.3, 0.45, 0.22]], speed: 0.8 },
  { id: 'oil-gallery', kind: 'oil', label: 'Главная магистраль', points: [[1.3, 0.45, 0.22], [0.86, 0.45, 0.22], [0.86, 0.42, 0.05]], speed: 0.8 },
  { id: 'oil-head', kind: 'oil', label: 'К распредвалам и VANOS', points: [[1.3, 0.47, 0.2], [1.32, 0.72, 0.12], [1.25, 0.75, 0.05], [0.86, 0.75, 0.05]], speed: 0.7 },
  { id: 'oil-turbo', kind: 'oil', label: 'Смазка турбины', points: [[1.22, 0.45, -0.18], [1.1, 0.55, -0.32], [1.01, 0.62, -0.36], [0.98, 0.45, -0.3], [1.0, 0.3, -0.12]], speed: 0.8, density: 22 },
  { id: 'oil-return', kind: 'oil', label: 'Слив', points: [[0.86, 0.74, -0.05], [0.84, 0.5, -0.1], [0.9, 0.3, -0.05]], speed: 0.5 },
  // COOLANT
  { id: 'cool-jacket', kind: 'coolant', label: 'Рубашка блока', points: [[1.42, 0.46, 0], [1.25, 0.5, 0.22], [0.88, 0.52, 0.22], [0.88, 0.72, 0.05], [1.38, 0.73, 0.1]], gradient: ['#3ddc97', '#ff7b54'] },
  { id: 'cool-hot', kind: 'coolant', label: 'Горячая → радиатор', points: [[1.38, 0.73, 0.1], [1.7, 0.72, 0.05], [2.12, 0.7, 0.0]], gradient: ['#ff7b54', '#ff9b6b'] },
  { id: 'cool-rad', kind: 'coolant', label: 'Через радиатор', points: [[2.12, 0.7, -0.3], [2.12, 0.52, -0.32], [2.12, 0.35, -0.3]], gradient: ['#ff9b6b', '#3ddc97'] },
  { id: 'cool-return', kind: 'coolant', label: 'Холодная → помпа', points: [[2.12, 0.34, 0], [1.75, 0.34, 0], [1.46, 0.46, 0]], gradient: ['#3ddc97', '#3ddc97'] },
  { id: 'cool-cac', kind: 'coolant', label: 'Контур охлаждения наддува', points: [[1.1, 0.75, 0.38], [1.6, 0.6, 0.45], [2.18, 0.45, 0.35], [2.0, 0.42, 0.2], [1.3, 0.62, 0.38]], gradient: ['#ff9b6b', '#3ddc97'], speed: 0.6 },
  { id: 'cool-heater', kind: 'coolant', label: 'Печка', points: [[0.88, 0.72, 0.05], [0.6, 0.74, 0.1], [0.44, 0.72, 0.05], [0.6, 0.5, -0.1], [1.42, 0.46, -0.05]], gradient: ['#ff7b54', '#3ddc97'], speed: 0.6 },
  // ELECTRIC
  { id: 'elec-starter', kind: 'electric', label: 'АКБ (багажник) → стартер', points: [[-2.15, 0.6, -0.55], [-1.8, 0.24, -0.62], [-0.5, 0.2, -0.62], [0.5, 0.22, -0.55], [0.75, 0.32, 0.0], [0.84, 0.38, 0.2]], speed: 2.4 },
  { id: 'elec-charge', kind: 'electric', label: 'Генератор → АКБ', points: [[1.45, 0.5, 0.28], [1.2, 0.3, -0.2], [0.5, 0.18, -0.5], [-0.5, 0.18, -0.6], [-1.8, 0.2, -0.6], [-2.15, 0.56, -0.48]], speed: 2.0 },
  { id: 'elec-ecu', kind: 'electric', label: 'DME → катушки зажигания', points: [[1.72, 0.66, 0.56], [1.4, 0.86, 0.2], [1.29, 0.87, 0.0], [0.9, 0.87, 0.0]], speed: 2.0 },
  { id: 'elec-inj', kind: 'electric', label: 'DME → форсунки', points: [[1.72, 0.66, 0.56], [1.45, 0.72, 0.3], [1.3, 0.74, 0.2], [0.9, 0.74, 0.2]], speed: 2.0 },
  { id: 'elec-lights', kind: 'electric', label: 'Фары', points: [[1.72, 0.66, 0.56], [2.1, 0.7, 0.62], [2.25, 0.73, 0.68]], speed: 1.8 },
  { id: 'elec-rear', kind: 'electric', label: 'Задние фонари', points: [[-2.15, 0.6, -0.55], [-2.4, 0.9, -0.65], [-2.56, 0.96, -0.72]], speed: 1.8 },
  { id: 'elec-info', kind: 'electric', label: 'iDrive и приборы', points: [[0.5, 0.25, -0.55], [0.3, 0.7, -0.2], [0.22, 1.03, 0.0], [0.24, 0.98, 0.38]], speed: 1.8 },
  // HYDRAULIC (brake fluid)
  { id: 'brake-master', kind: 'hydraulic', label: 'Главный цилиндр → DSC', points: [[0.88, 0.83, 0.42], [1.2, 0.86, 0.0], [1.6, 0.72, -0.5]], speed: 1.4 },
  { id: 'brake-fr', kind: 'hydraulic', label: 'Переднее правое', points: [[1.62, 0.6, -0.6], [1.55, 0.45, -0.66], [1.55, 0.42, -0.74]], speed: 1.4 },
  { id: 'brake-fl', kind: 'hydraulic', label: 'Переднее левое', points: [[1.6, 0.62, -0.5], [1.7, 0.5, 0.0], [1.6, 0.45, 0.6], [1.55, 0.42, 0.74]], speed: 1.4 },
  { id: 'brake-rear', kind: 'hydraulic', label: 'Задний контур', points: [[1.55, 0.6, -0.58], [1.0, 0.22, -0.48], [-0.6, 0.2, -0.45], [-1.3, 0.3, -0.2], [-1.38, 0.34, 0]], speed: 1.4 },
  { id: 'brake-rr', kind: 'hydraulic', label: 'Заднее правое', points: [[-1.38, 0.34, 0], [-1.42, 0.38, -0.45], [-1.42, 0.42, -0.74]], speed: 1.4 },
  { id: 'brake-rl', kind: 'hydraulic', label: 'Заднее левое', points: [[-1.38, 0.34, 0], [-1.42, 0.38, 0.45], [-1.42, 0.42, 0.74]], speed: 1.4 },
  // A/C
  { id: 'ac-loop', kind: 'refrigerant', label: 'Компрессор → конденсатор', points: [[1.46, 0.36, -0.3], [1.85, 0.34, -0.4], [2.19, 0.42, -0.3], [2.19, 0.62, 0.2]], speed: 0.9 },
  { id: 'ac-loop2', kind: 'refrigerant', label: 'Конденсатор → испаритель', points: [[2.19, 0.64, 0.3], [1.7, 0.72, 0.5], [0.85, 0.82, 0.2], [0.46, 0.76, 0.1]], speed: 0.9 },
  { id: 'ac-loop3', kind: 'refrigerant', label: 'Испаритель → компрессор', points: [[0.46, 0.68, -0.1], [0.8, 0.5, -0.3], [1.38, 0.38, -0.3]], speed: 0.9 },
]

const C = (c: ComponentDef) => c
const shotAt = (x: number, y: number, z: number, d = 1.4): ComponentDef['shot'] => ({ pos: [x + d * 0.9, y + d * 0.55, z + d * 1.1], target: [x, y, z] })
const inCabin = (target: [number, number, number], pos: [number, number, number] = [-0.28, 1.04, 0.38]) => ({ pos, target, via: [-0.2, 1.0, 1.8] as [number, number, number] })

const components: ComponentDef[] = [
  // ENGINE
  C({ id: 'engine', name: 'Engine', ru: 'Двигатель', system: 'engine', pos: [1.1, 0.88, 0], hotspot: true, lab: 'cylinder', flows: ['fuel', 'air', 'exhaust'],
    beginner: 'Бензиновый двигатель: внутри цилиндров смесь воздуха и бензина поджигается искрой, а взрывы толкают поршни.', engineer: 'Рядная «четвёрка» 2,0 л с турбонаддувом TwinPower Turbo, непосредственным впрыском, Valvetronic и Double-VANOS. Стоит продольно, почти целиком за передней осью.',
    varies: 'Мощность и обновления двигателя зависят от года выпуска и рынка.', keywords: ['engine', 'мотор', 'двигатель', 'b48', 'petrol', 'бензин'], shot: { pos: [2.45, 1.55, 1.25], target: [1.1, 0.6, 0], via: [3.8, 2.2, 1.2] } }),
  C({ id: 'cylinders', name: 'Cylinders', ru: 'Цилиндры', system: 'engine', pos: [1.1, 0.6, 0.2], lab: 'cylinder', flows: ['fuel', 'air'],
    beginner: 'Четыре цилиндра — камеры, в которых сгорает смесь.', engineer: 'Рабочий объём ~0,5 л на цилиндр; 4 такта за 720°, порядок работы 1-3-4-2.', keywords: ['cylinder', 'цилиндр'], shot: shotAt(1.1, 0.6, 0, 0.8) }),
  C({ id: 'pistons', name: 'Pistons', ru: 'Поршни', system: 'engine', pos: [1.03, 0.6, -0.05], lab: 'cylinder',
    beginner: 'Расширяющиеся газы толкают поршень вниз — так энергия бензина становится движением.', engineer: 'Лёгкие алюминиевые поршни; масляные форсунки охлаждают их днище снизу.', keywords: ['piston', 'поршень'], shot: { pos: [1.7, 0.7, 1.0], target: [1.03, 0.56, 0] } }),
  C({ id: 'connectingRods', name: 'Connecting rods', ru: 'Шатуны', system: 'engine', pos: [1.16, 0.5, 0], lab: 'cylinder',
    beginner: 'Шатуны связывают поршни с коленвалом.', engineer: 'Кривошипно-шатунный механизм превращает силу давления в крутящий момент.', keywords: ['rod', 'шатун'], shot: { pos: [1.8, 0.48, 1.0], target: [1.14, 0.48, 0] } }),
  C({ id: 'crankshaft', name: 'Crankshaft', ru: 'Коленчатый вал', system: 'engine', pos: [1.1, 0.4, 0.05], lab: 'cylinder',
    beginner: 'Коленвал превращает движение поршней вверх-вниз во вращение.', engineer: 'Вал с балансирными валами второго порядка гасит вибрации рядной «четвёрки».', keywords: ['crank', 'коленвал'], shot: { pos: [1.85, 0.28, 1.1], target: [1.1, 0.42, 0] } }),
  C({ id: 'cylinderHead', name: 'Cylinder head', ru: 'Головка блока', system: 'engine', pos: [1.1, 0.77, 0.15],
    beginner: 'Наверху — клапаны, распредвалы, свечи и форсунки.', engineer: 'Valvetronic плавно меняет ход впускных клапанов и регулирует нагрузку почти без дроссельной заслонки. Double-VANOS сдвигает фазы обоих распредвалов.', keywords: ['head', 'valvetronic', 'vanos', 'клапаны'], shot: shotAt(1.1, 0.76, 0, 0.8) }),
  C({ id: 'sparkPlugs', name: 'Spark plugs', ru: 'Свечи зажигания', system: 'engine', pos: [1.16, 0.88, 0.0], lab: 'cylinder', flows: ['electric'], path: ['elec-ecu'],
    beginner: 'Свеча даёт искру и поджигает смесь в нужный момент. У каждого цилиндра своя катушка.', engineer: 'Индивидуальные катушки создают десятки киловольт; угол опережения зажигания DME меняет по оборотам, нагрузке и сигналу датчиков детонации.', keywords: ['spark', 'свеча', 'зажигание', 'ignition'], shot: shotAt(1.16, 0.85, 0, 0.6) }),
  C({ id: 'turbo', name: 'Turbocharger', ru: 'Турбокомпрессор', system: 'engine', pos: [1.0, 0.6, -0.36], hotspot: true, lab: 'turbo', flows: ['air', 'exhaust', 'oil'], path: ['air-turbo', 'air-boost', 'exh-manifold', 'exh-main', 'oil-turbo'],
    beginner: 'Выхлоп крутит турбинку, а она через вал крутит компрессор, который нагнетает воздух в двигатель.', engineer: 'Twin-scroll турбина: импульсы цилиндров 1-4 и 2-3 разделены, поэтому турбина раскручивается быстрее. Перепускной клапан (wastegate) ограничивает давление наддува.', keywords: ['turbo', 'турбина', 'турбо', 'наддув', 'where is the turbo'], shot: { pos: [1.75, 1.05, -1.4], target: [1.0, 0.58, -0.36] } }),
  C({ id: 'intercooler', name: 'Charge-air cooler', ru: 'Охладитель наддува', system: 'engine', pos: [1.1, 0.78, 0.31], flows: ['air', 'coolant'], path: ['air-boost', 'air-manifold', 'cool-cac'],
    beginner: 'Охлаждает сжатый воздух. Холодный воздух плотнее, в цилиндр его помещается больше.', engineer: 'Жидкостный (water-to-air) охладитель встроен во впускной коллектор; отдельный низкотемпературный контур с насосом и радиатором впереди. Короткий тракт — быстрый отклик.', keywords: ['intercooler', 'интеркулер'], shot: shotAt(1.1, 0.72, 0.31, 0.8) }),
  C({ id: 'airFilter', name: 'Air intake', ru: 'Впуск и фильтр', system: 'engine', pos: [1.75, 0.86, 0.34], flows: ['air'], path: ['air-intake', 'air-turbo'],
    beginner: 'Воздух заходит через решётку и очищается фильтром.', engineer: 'Датчики массового расхода/давления во впуске сообщают DME, сколько воздуха поступает.', keywords: ['air filter', 'впуск', 'intake'], shot: shotAt(1.75, 0.78, 0.34, 0.9) }),
  C({ id: 'oilPump', name: 'Oil pump', ru: 'Масляный насос', system: 'engine', pos: [1.32, 0.3, 0.05], flows: ['oil'], path: ['oil-pump', 'oil-gallery', 'oil-head', 'oil-turbo', 'oil-return'],
    beginner: 'Масло забирается из поддона и подаётся ко всем подшипникам, валам и турбине.', engineer: 'Насос с регулируемой подачей; давление масла также управляет фазовращателями VANOS.', keywords: ['oil', 'масло', 'насос'], shot: shotAt(1.32, 0.32, 0, 0.9) }),
  // FUEL
  C({ id: 'fuelTank', name: 'Fuel tank', ru: 'Топливный бак', system: 'fuel', pos: [-1.0, 0.48, 0.3], hotspot: true, flows: ['fuel'], path: ['fuel-supply', 'fuel-evap'],
    beginner: 'Бак под задним сиденьем. Он похож на седло: посередине через него проходит карданный вал.', engineer: 'Седловидный бак из двух половин; струйный насос перекачивает топливо из одной половины в другую, чтобы насос не «голодал» в поворотах.', varies: 'Объём бака зависит от версии.', keywords: ['tank', 'бак', 'fuel tank', 'где бак'], shot: { pos: [-0.4, 0.15, 2.4], target: [-1.0, 0.33, 0.2] } }),
  C({ id: 'feedPump', name: 'Fuel pump', ru: 'Топливный насос', system: 'fuel', pos: [-0.85, 0.42, 0.33], flows: ['fuel'], path: ['fuel-supply'],
    beginner: 'Электронасос в баке подаёт бензин к двигателю.', engineer: 'Насос низкого давления (несколько бар) с регулированием по потребности; фильтр тонкой очистки встроен в модуль бака.', keywords: ['fuel pump', 'насос'], shot: shotAt(-0.85, 0.36, 0.33, 1.0) }),
  C({ id: 'fuelFilter', name: 'Fuel line', ru: 'Топливная магистраль', system: 'fuel', pos: [-0.2, 0.24, 0.46], flows: ['fuel'], path: ['fuel-supply'],
    beginner: 'Трубка под днищем ведёт бензин к моторному отсеку.', engineer: 'Магистраль низкого давления вдоль тоннеля; пары бензина из бака собирает угольный адсорбер и двигатель потом их сжигает.', keywords: ['fuel line', 'магистраль', 'evap'], shot: { pos: [0.4, -0.1, 1.8], target: [-0.2, 0.22, 0.4] } }),
  C({ id: 'hpPump', name: 'High-pressure pump', ru: 'ТНВД', system: 'fuel', pos: [0.85, 0.82, 0.12], flows: ['fuel'], path: ['fuel-supply', 'fuel-hp'],
    gauge: { label: 'Давление впрыска', value: 200, max: 350, unit: 'бар', note: 'Порядок величины для бензинового непосредственного впрыска; у новых моторов выше' },
    beginner: 'Насос на головке блока сжимает бензин до высокого давления для впрыска прямо в цилиндр.', engineer: 'Одноплунжерный насос с приводом от кулачка распредвала; клапан дозирования поддерживает заданное давление в рампе.', keywords: ['pump', 'тнвд', 'high pressure'], shot: shotAt(0.85, 0.78, 0.12, 0.7) }),
  C({ id: 'injectors', name: 'Injectors', ru: 'Форсунки', system: 'fuel', pos: [1.16, 0.72, 0.15], flows: ['fuel'], path: ['fuel-hp', 'fuel-inj-0', 'fuel-inj-1', 'fuel-inj-2', 'fuel-inj-3'], lab: 'cylinder',
    beginner: 'Форсунки впрыскивают бензин прямо в цилиндр. Испаряясь, он ещё и охлаждает воздух.', engineer: 'Многоструйные форсунки непосредственного впрыска; впрыск на такте впуска и иногда разделённый — для холодного пуска и прогрева катализатора.', keywords: ['injector', 'форсунка', 'впрыск'], shot: shotAt(1.16, 0.7, 0.15, 0.6) }),
  // EXHAUST
  C({ id: 'exhaustManifold', name: 'Exhaust manifold', ru: 'Выпускной коллектор', system: 'exhaust', pos: [0.95, 0.68, -0.3], flows: ['exhaust'], path: ['exh-port-0', 'exh-port-1', 'exh-port-2', 'exh-port-3', 'exh-manifold'],
    beginner: 'Собирает горячие газы и ведёт их к турбине.', engineer: 'Каналы разделены попарно (1-4 и 2-3) для twin-scroll турбины.', keywords: ['manifold', 'коллектор'], shot: shotAt(0.95, 0.66, -0.3, 0.8) }),
  C({ id: 'catalyst', name: 'Catalytic converter', ru: 'Катализатор', system: 'exhaust', pos: [0.78, 0.36, -0.3], hotspot: true, flows: ['exhaust'], path: ['exh-main'],
    beginner: 'Катализатор превращает вредные газы в углекислый газ, воду и азот.', engineer: 'Трёхкомпонентный катализатор сразу за турбиной — быстро прогревается. Лямбда-зонды держат смесь стехиометрической (~14,7 : 1). В части рынков добавлен сажевый фильтр OPF.', varies: 'Наличие сажевого фильтра (OPF) зависит от рынка и года.', keywords: ['catalyst', 'катализатор', 'лямбда', 'opf'], shot: { pos: [1.3, 0.0, -1.6], target: [0.78, 0.32, -0.3] } }),
  C({ id: 'muffler', name: 'Muffler', ru: 'Глушитель', system: 'exhaust', pos: [-2.28, 0.4, -0.2], flows: ['exhaust'], path: ['exh-main'],
    beginner: 'Глушитель гасит звук, газы выходят наружу.', engineer: 'Поперечный задний глушитель; управляемые заслонки на части версий меняют звук.', keywords: ['muffler', 'глушитель'], shot: shotAt(-2.28, 0.32, -0.2, 1.0) }),
  // TRANSMISSION
  C({ id: 'transmission', name: '8-speed automatic', ru: 'Коробка передач', system: 'transmission', pos: [0.35, 0.58, 0.2], hotspot: true, lab: 'transmission',
    beginner: 'Автомат с восемью передачами: на низких — тяга для разгона, на высоких — низкие обороты и экономия.', engineer: 'Гидромеханический 8-ступенчатый автомат: четыре планетарных ряда и пять фрикционных элементов, в каждой передаче замкнуты три из них.', keywords: ['gearbox', 'коробка', 'transmission', 'акпп', 'zf'], shot: { pos: [0.9, 1.25, 1.55], target: [0.32, 0.4, 0] } }),
  C({ id: 'torqueConverter', name: 'Torque converter', ru: 'Гидротрансформатор', system: 'transmission', pos: [0.7, 0.42, 0.2], lab: 'transmission',
    beginner: 'Мягко соединяет мотор и коробку через масло.', engineer: 'Гидротрансформатор с блокировкой и гасителем крутильных колебаний; на ходу почти всегда заблокирован.', keywords: ['torque converter', 'гидротрансформатор'], shot: shotAt(0.7, 0.4, 0, 0.8) }),
  C({ id: 'driveshaft', name: 'Driveshaft', ru: 'Карданный вал', system: 'transmission', pos: [-0.6, 0.38, 0],
    beginner: 'Вал передаёт вращение от коробки назад, к ведущим задним колёсам.', engineer: 'Двухсекционный кардан с промежуточной опорой; проходит в тоннеле через «седло» бака.', keywords: ['driveshaft', 'кардан'], shot: shotAt(-0.6, 0.34, 0, 1.2) }),
  C({ id: 'rearDiff', name: 'Rear differential', ru: 'Задний дифференциал', system: 'transmission', pos: [-1.49, 0.38, 0], lab: 'transmission',
    beginner: 'Поворачивает вращение к колёсам и позволяет им крутиться с разной скоростью в повороте.', engineer: 'Главная передача с гипоидным зацеплением и открытым дифференциалом; полуоси с ШРУСами.', varies: 'Полноприводная версия xDrive имеет раздаточную коробку и передний мост.', keywords: ['differential', 'дифференциал', 'xdrive'], shot: { pos: [-2.7, 0.55, 1.3], target: [-1.49, 0.34, 0] } }),
  // COOLING
  C({ id: 'radiator', name: 'Radiator', ru: 'Радиатор', system: 'cooling', pos: [2.12, 0.74, 0.25], hotspot: true, flows: ['coolant'], path: ['cool-jacket', 'cool-hot', 'cool-rad', 'cool-return'],
    beginner: 'Горячая жидкость отдаёт тепло воздуху в радиаторе и возвращается в мотор холодной.', engineer: 'Основной контур с термостатом, управляемым картой: при спокойной езде двигатель держится горячее (меньше трения), под нагрузкой — холоднее.', keywords: ['radiator', 'радиатор', 'cooling', 'охлаждение'], shot: { pos: [3.4, 1.0, 1.0], target: [2.1, 0.5, 0] } }),
  C({ id: 'waterPump', name: 'Water pump', ru: 'Помпа', system: 'cooling', pos: [1.44, 0.46, 0.06], flows: ['coolant'], path: ['cool-return', 'cool-jacket'],
    beginner: 'Насос гонит жидкость по кругу через мотор и радиатор.', engineer: 'Помпа с возможностью отключения на прогреве — двигатель быстрее выходит на рабочую температуру.', keywords: ['water pump', 'помпа'], shot: shotAt(1.44, 0.46, 0, 0.7) }),
  C({ id: 'thermostat', name: 'Thermostat', ru: 'Термостат', system: 'cooling', pos: [1.38, 0.74, 0.12], flows: ['coolant'],
    beginner: 'Не пускает жидкость в радиатор, пока мотор холодный.', engineer: 'Термостат с электроподогревом позволяет DME сдвигать рабочую температуру.', keywords: ['thermostat', 'термостат'], shot: shotAt(1.38, 0.72, 0.12, 0.6) }),
  C({ id: 'radiatorFan', name: 'Radiator fan', ru: 'Вентилятор', system: 'cooling', pos: [2.03, 0.52, -0.25],
    beginner: 'Протягивает воздух через радиатор в пробке и на стоянке.', engineer: 'Электровентилятор с плавным управлением.', keywords: ['fan', 'вентилятор'], shot: shotAt(2.03, 0.52, 0, 0.9) }),
  // ELECTRICAL
  C({ id: 'battery', name: 'Battery', ru: 'Аккумулятор', system: 'electrical', pos: [-2.15, 0.7, -0.55], hotspot: true, flows: ['electric'], path: ['elec-starter', 'elec-charge'],
    beginner: 'Аккумулятор спрятан в багажнике, справа под полом. Так передняя ось легче, а развесовка ближе к 50 : 50.', engineer: 'АКБ 12 В (AGM) в багажнике; толстый плюсовой кабель идёт под полом к моторному отсеку, где есть клемма для прикуривания.', keywords: ['battery', 'аккумулятор', 'акб', '12v'], shot: { pos: [-3.4, 1.35, -1.2], target: [-2.15, 0.55, -0.5] } }),
  C({ id: 'starter', name: 'Starter', ru: 'Стартер', system: 'electrical', pos: [0.84, 0.44, 0.24], flows: ['electric'], path: ['elec-starter'], action: 'engineStart',
    beginner: 'Раскручивает двигатель при пуске.', engineer: 'Усиленный стартер рассчитан на частые пуски системы Auto Start/Stop.', keywords: ['starter', 'стартер', 'запуск'], shot: shotAt(0.84, 0.38, 0.24, 0.8) }),
  C({ id: 'alternator', name: 'Alternator', ru: 'Генератор', system: 'electrical', pos: [1.45, 0.58, 0.22], flows: ['electric'], path: ['elec-charge'],
    beginner: 'Вырабатывает электричество, пока работает мотор, и заряжает аккумулятор.', engineer: 'Интеллектуальное управление генератором: больше заряжает при торможении, меньше — при разгоне.', keywords: ['alternator', 'генератор'], shot: shotAt(1.45, 0.5, 0.22, 0.7) }),
  C({ id: 'ecu', name: 'DME (engine ECU)', ru: 'Блок управления двигателем', system: 'electrical', pos: [1.72, 0.7, 0.56], flows: ['electric'], path: ['elec-ecu', 'elec-inj'],
    beginner: '«Мозг» двигателя: решает, сколько бензина впрыснуть и когда дать искру.', engineer: 'DME управляет впрыском, зажиганием, Valvetronic, VANOS, наддувом и термоменеджментом; общается с коробкой и DSC по шинам данных.', keywords: ['ecu', 'dme', 'эбу', 'компьютер'], shot: shotAt(1.72, 0.66, 0.56, 0.8) }),
  C({ id: 'lights', name: 'Lights', ru: 'Фары и фонари', system: 'electrical', pos: [2.25, 0.8, 0.68], flows: ['electric'], path: ['elec-lights', 'elec-rear'],
    beginner: 'Освещение питается от сети 12 В.', engineer: 'Светодиодная оптика с управлением от кузовного блока.', keywords: ['lights', 'фары'], shot: shotAt(2.25, 0.72, 0.68, 1.0) }),
  // BRAKES
  C({ id: 'brakes', name: 'Brakes', ru: 'Тормоза', system: 'brakes', pos: [1.6, 0.52, 0.74], hotspot: true, lab: 'brakes', flows: ['hydraulic'], path: ['brake-master', 'brake-fr', 'brake-fl', 'brake-rear', 'brake-rr', 'brake-rl'], action: 'brake',
    beginner: 'Колодки прижимаются к дискам, и трение превращает скорость в тепло.', engineer: 'Дисковые тормоза на всех колёсах, спереди вентилируемые; двухконтурный гидропривод с вакуумным усилителем.', keywords: ['brake', 'тормоз', 'тормоза'], shot: { pos: [2.5, 0.65, 1.7], target: [1.49, 0.34, 0.75] } }),
  C({ id: 'masterCylinder', name: 'Master cylinder', ru: 'Главный тормозной цилиндр', system: 'brakes', pos: [0.86, 0.86, 0.42], flows: ['hydraulic'], path: ['brake-master'], lab: 'brakes',
    beginner: 'Нажатие педали выдавливает тормозную жидкость к колёсам.', engineer: 'Тандемный цилиндр с вакуумным усилителем.', keywords: ['master cylinder', 'главный цилиндр'], shot: shotAt(0.82, 0.8, 0.42, 0.7) }),
  C({ id: 'absUnit', name: 'DSC / ABS unit', ru: 'Блок DSC (ABS)', system: 'brakes', pos: [1.62, 0.74, -0.55], flows: ['hydraulic'], path: ['brake-master', 'brake-fr', 'brake-fl', 'brake-rear'], lab: 'brakes',
    beginner: 'Не даёт колёсам заблокироваться при резком торможении и помогает удержать машину от заноса.', engineer: 'DSC: гидроблок с клапанами и насосом; ABS, контроль тяги и стабилизация подтормаживают отдельные колёса по сигналам датчиков скорости, рыскания и угла руля.', keywords: ['abs', 'esp', 'dsc', 'антиблокировочная', 'стабилизация'], shot: shotAt(1.62, 0.66, -0.55, 0.8) }),
  // STEERING
  C({ id: 'steeringWheel', name: 'Steering wheel', ru: 'Руль', system: 'steering', pos: [0.18, 1.02, 0.38], action: 'steer',
    beginner: 'Руль через вал поворачивает рейку и передние колёса.', engineer: 'Датчик момента на валу сообщает электроусилителю, с какой силой помогать.', keywords: ['steering', 'руль'], shot: inCabin([0.3, 0.9, 0.38]) }),
  C({ id: 'steeringRack', name: 'Steering rack (EPS)', ru: 'Рейка с электроусилителем', system: 'steering', pos: [1.32, 0.42, 0.3], action: 'steer',
    beginner: 'Рейка двигает колёса влево-вправо, электромотор помогает её крутить.', engineer: 'Электромеханический усилитель на рейке; работает только когда нужен и позволяет ассистентам удержания полосы подруливать.', varies: 'Активное подруливание задних колёс — опция.', keywords: ['rack', 'рейка', 'eps', 'усилитель'], shot: { pos: [2.2, 0.55, 1.2], target: [1.32, 0.36, 0] } }),
  // SUSPENSION
  C({ id: 'frontSusp', name: 'Front suspension', ru: 'Передняя подвеска', system: 'suspension', pos: [1.49, 0.62, -0.6], action: 'drive',
    beginner: 'Пружины и амортизаторы гасят неровности, а рычаги держат колесо под правильным углом.', engineer: 'Двухрычажная подвеска с разнесёнными функциями: стабильная геометрия в повороте и комфорт.', keywords: ['suspension', 'подвеска', 'пружина', 'амортизатор'], shot: { pos: [2.4, 0.7, -1.6], target: [1.49, 0.45, -0.6] } }),
  C({ id: 'rearSusp', name: 'Rear suspension', ru: 'Задняя подвеска', system: 'suspension', pos: [-1.49, 0.6, 0.55], action: 'drive',
    beginner: 'Независимая подвеска: каждое заднее колесо работает отдельно.', engineer: 'Многорычажная (5-link) задняя подвеска на подрамнике; каждый рычаг отвечает за своё направление сил.', keywords: ['rear suspension', 'многорычажка'], shot: { pos: [-2.9, 0.65, 1.6], target: [-1.49, 0.4, 0] } }),
  C({ id: 'subframes', name: 'Subframes', ru: 'Подрамники', system: 'suspension', pos: [1.43, 0.42, 0.45],
    beginner: 'У седана нет отдельной рамы: кузов несущий, а подвеска крепится к подрамникам.', engineer: 'Несущий кузов + подрамники на сайлентблоках изолируют шум и вибрации.', keywords: ['subframe', 'подрамник', 'кузов'], shot: { pos: [0.5, -0.4, 2.4], target: [0, 0.3, 0] } }),
  // CABIN
  C({ id: 'dashboard', name: 'Dashboard', ru: 'Приборная панель', system: 'cabin', pos: [0.42, 0.98, 0.0],
    beginner: 'Приборы, экран iDrive, климат, подушка пассажира.', engineer: 'За панелью — блок климата (HVAC), каркас, проводка, блоки управления.', keywords: ['dashboard', 'панель'], shot: inCabin([0.5, 0.88, 0], [-0.3, 1.06, 0.05]) }),
  C({ id: 'cluster', name: 'Instrument cluster', ru: 'Приборы', system: 'cabin', pos: [0.24, 1.03, 0.42],
    beginner: 'Цифровые приборы: скорость, обороты, подсказки.', engineer: 'Комбинация приборов получает данные от DME, коробки и DSC по шинам данных.', keywords: ['cluster', 'приборы'], shot: inCabin([0.25, 0.98, 0.42]) }),
  C({ id: 'infotainment', name: 'iDrive', ru: 'Мультимедиа iDrive', system: 'cabin', pos: [0.22, 1.08, 0.0],
    beginner: 'Экран и контроллер для навигации, музыки и настроек.', engineer: 'Головное устройство в сети автомобиля; через неё также обновляется ПО и идёт диагностика.', keywords: ['idrive', 'screen', 'экран', 'мультимедиа'], shot: inCabin([0.3, 1.0, 0], [-0.28, 1.05, 0.12]) }),
  C({ id: 'airbag', name: 'Airbag', ru: 'Подушка безопасности', system: 'cabin', pos: [0.1, 0.95, 0.38], action: 'airbag',
    beginner: 'При ударе подушка надувается за доли секунды.', engineer: 'Датчики → блок SRS → газогенератор: раскрытие за десятки миллисекунд; ремни с преднатяжителями срабатывают раньше.', keywords: ['airbag', 'подушка'], shot: inCabin([0.15, 0.9, 0.38], [-0.28, 1.07, 0.6]) }),
  C({ id: 'seats', name: 'Seats & belts', ru: 'Сиденья и ремни', system: 'cabin', pos: [-0.4, 0.95, -0.42],
    beginner: 'Пять мест, ремни с преднатяжителями.', engineer: 'Ремни с ограничителями усилия; задний ряд с креплениями ISOFIX.', keywords: ['seat', 'сиденья', 'ремни'], shot: { pos: [-1.9, 1.15, 0.0], target: [-0.3, 0.75, 0] } }),
  C({ id: 'hvac', name: 'Air conditioning', ru: 'Кондиционер', system: 'climate', pos: [0.42, 0.82, -0.2], flows: ['refrigerant', 'air'], path: ['ac-loop', 'ac-loop2', 'ac-loop3', 'air-cabin'],
    beginner: 'Кондиционер забирает тепло из салона и выбрасывает его через радиатор спереди.', engineer: 'Компрессор → конденсатор → расширительный клапан → испаритель; климат-контроль по зонам смешивает холодный и тёплый воздух заслонками.', keywords: ['ac', 'кондиционер', 'климат'], shot: shotAt(0.42, 0.75, 0, 1.0) }),
  C({ id: 'acCompressor', name: 'A/C compressor', ru: 'Компрессор кондиционера', system: 'climate', pos: [1.46, 0.42, -0.24], flows: ['refrigerant'], path: ['ac-loop', 'ac-loop2', 'ac-loop3'],
    beginner: 'Сжимает хладагент, работает от ремня двигателя.', engineer: 'Компрессор с регулируемой производительностью.', keywords: ['compressor'], shot: shotAt(1.46, 0.36, -0.24, 0.7) }),
  // TRUNK
  C({ id: 'trunk', name: 'Trunk', ru: 'Багажник', system: 'trunk', pos: [-2.15, 0.85, 0.2], action: 'openTrunk',
    beginner: 'Под полом багажника справа — аккумулятор. Запаски часто нет: шины Run-Flat или ремкомплект.', engineer: 'Аккумулятор в багажнике улучшает развесовку; рядом блоки управления и задний глушитель под полом.', varies: 'Запасное колесо, Run-Flat или ремкомплект — зависит от рынка и комплектации.', keywords: ['trunk', 'багажник', 'boot', 'запаска'], shot: { pos: [-4.0, 1.55, 0.7], target: [-2.1, 0.7, 0] } }),
]

const walk: WalkZone[] = [
  { id: 'front', label: 'FRONT', shot: { pos: [5.6, 1.3, 2.6], target: [1.4, 0.6, 0] } },
  { id: 'bay', label: 'ENGINE BAY', shot: { pos: [2.5, 1.6, 1.1], target: [1.1, 0.6, 0], via: [4.0, 2.2, 1.2] }, xray: true, open: ['hood'], focus: ['engine'] },
  { id: 'left', label: 'LEFT SIDE', shot: { pos: [0.0, 1.2, 5.8], target: [0, 0.65, 0] } },
  { id: 'door', label: 'DRIVER DOOR', shot: { pos: [-0.3, 1.15, 2.3], target: [0.1, 0.8, 0.4] }, open: ['door'] },
  { id: 'cabin', label: 'CABIN', shot: { pos: [-1.05, 1.3, 0.02], target: [0.45, 0.8, 0.3], via: [-0.5, 1.2, 1.7] }, xray: true },
  { id: 'rear', label: 'REAR SEATS', shot: { pos: [-2.0, 1.15, 0.0], target: [-0.3, 0.75, 0] }, xray: true },
  { id: 'trunk', label: 'TRUNK', shot: { pos: [-4.0, 1.55, 0.6], target: [-2.1, 0.7, 0] }, open: ['trunk'] },
  { id: 'axle', label: 'REAR AXLE', shot: { pos: [-3.0, 0.55, 1.8], target: [-1.49, 0.35, 0] }, xray: true, focus: ['suspension', 'transmission'] },
  { id: 'under', label: 'UNDERBODY', shot: { pos: [1.4, -1.6, 2.4], target: [-0.2, 0.3, 0] }, lift: true },
]

const step = (title: string, text: string, focus: string, extra: Partial<LearnStep> = {}): LearnStep => ({ title, text, focus, ...extra })

export const bmw530i: VehicleDef<CarLayout> = {
  id: 'bmw', kind: 'car', name: 'BMW 530i', line: 'PETROL · SEDAN', type: 'Turbo petrol · direct injection',
  tagline: 'Заднеприводный седан с турбированным бензиновым мотором.',
  representative: 'Representative BMW 530i (G30) petrol powertrain',
  varies: 'Exact configuration may vary by model year, engine and market.',
  accent: '#6cc6ff',
  specs: [
    { label: 'Engine', value: '2.0 L inline-4 turbo petrol' },
    { label: 'Injection', value: 'Direct injection' },
    { label: 'Gearbox', value: '8-speed automatic' },
    { label: 'Drive', value: 'RWD (xDrive optional)' },
    { label: 'Body', value: 'Unibody sedan' },
    { label: 'Size', value: '≈ 4.94 × 1.87 × 1.48 m' },
  ],
  systems: carSystems,
  components,
  flows,
  walk,
  overview: { pos: [6.4, 2.5, 6.9], target: [0, 0.6, 0] },
  layers: carLayers,
  scale: 1,
  awd: false,
  gears: { count: 8, label: '8-speed automatic' },
  checklist: [
    { label: 'Petrol', ids: ['engine', 'injectors', 'fuelTank', 'hpPump'] },
    { label: 'Combustion', ids: ['cylinders', 'sparkPlugs', 'pistons', 'crankshaft'] },
    { label: 'Turbo', ids: ['turbo', 'intercooler'] },
    { label: 'Transmission', ids: ['transmission', 'torqueConverter', 'rearDiff', 'driveshaft'] },
    { label: 'Brakes', ids: ['brakes', 'absUnit', 'masterCylinder'] },
    { label: 'Electrical', ids: ['battery', 'alternator', 'starter', 'ecu'] },
  ],
  start: carStart(false),
  powerPath: {
    title: 'HOW PETROL BECOMES MOTION',
    steps: [
      step('FUEL TANK', 'Бензин хранится в баке-«седле» под задним сиденьем.', 'fuelTank', { flows: ['fuel'], paths: ['fuel-supply'] }),
      step('FUEL PUMP', 'Электронасос в баке подаёт бензин к двигателю.', 'feedPump', { paths: ['fuel-supply'] }),
      step('FUEL SYSTEM', 'ТНВД на головке поднимает давление для впрыска.', 'hpPump', { paths: ['fuel-supply', 'fuel-hp'] }),
      step('INJECTORS', 'Форсунки впрыскивают бензин прямо в цилиндры.', 'injectors', { paths: ['fuel-hp', 'fuel-inj-0', 'fuel-inj-1', 'fuel-inj-2', 'fuel-inj-3'], action: 'engineStart' }),
      step('INTAKE', 'Турбина нагнетает воздух, охладитель делает его плотнее.', 'intercooler', { flows: ['air'] }),
      step('CYLINDERS', 'В цилиндре воздух и бензин перемешиваются и сжимаются.', 'cylinders', { flows: ['air', 'fuel'] }),
      step('SPARK', 'Свеча даёт искру точно в нужный момент.', 'sparkPlugs', { paths: ['elec-ecu'] }),
      step('COMBUSTION', 'Смесь сгорает, давление резко растёт.', 'cylinders', { flows: ['fuel', 'exhaust'] }),
      step('PISTONS', 'Давление толкает поршни вниз.', 'pistons'),
      step('CRANKSHAFT', 'Коленвал превращает толчки во вращение.', 'crankshaft'),
      step('TRANSMISSION', '8-ступенчатый автомат выбирает передачу.', 'transmission', { action: 'drive' }),
      step('DRIVESHAFT', 'Кардан несёт вращение назад.', 'driveshaft'),
      step('DIFFERENTIAL', 'Дифференциал делит вращение между задними колёсами.', 'rearDiff'),
      step('WHEELS', 'Задние колёса толкают машину вперёд.', 'rearSusp', { shot: { pos: [3.2, 0.9, 4.4], target: [0, 0.4, 0] } }),
    ],
  },
  learn: [
    step('STEP 01', 'Бензин идёт из бака к двигателю.', 'fuelTank', { flows: ['fuel'] }),
    step('STEP 02', 'Воздух поступает в цилиндры через турбину.', 'turbo', { flows: ['air'] }),
    step('STEP 03', 'Форсунка впрыскивает бензин.', 'injectors', { flows: ['fuel'], action: 'engineStart' }),
    step('STEP 04', 'Искра поджигает смесь — давление растёт.', 'sparkPlugs', { flows: ['electric'] }),
    step('STEP 05', 'Поршень движется вниз.', 'pistons'),
    step('STEP 06', 'Коленвал вращается.', 'crankshaft'),
    step('STEP 07', 'Мощность приходит в коробку передач.', 'transmission', { action: 'drive' }),
    step('STEP 08', 'Задние колёса вращаются, машина едет.', 'rearDiff', { shot: { pos: [4.2, 1.0, 4.6], target: [0, 0.45, 0] } }),
  ],
  demo: {
    id: 'demo-petrol', vehicle: 'bmw', title: 'How a spark creates power', subtitle: 'От капли бензина до вращения задних колёс',
    steps: [
      step('Бензин', 'Электронасос в баке подаёт бензин вперёд по магистрали.', 'feedPump', { paths: ['fuel-supply'], duration: 5 }),
      step('200 бар', 'ТНВД на головке блока сжимает его для непосредственного впрыска.', 'hpPump', { paths: ['fuel-hp'], duration: 5 }),
      step('Пуск', 'Стартер крутит двигатель, DME начинает впрыск.', 'starter', { action: 'engineStart', paths: ['elec-starter'], duration: 5 }),
      step('Воздух', 'Турбина нагнетает воздух, жидкостный охладитель делает его плотнее.', 'intercooler', { flows: ['air'], duration: 6 }),
      step('Искра', 'Свеча поджигает сжатую смесь — короткая вспышка, резкий рост давления.', 'sparkPlugs', { flows: ['fuel', 'electric'], duration: 6 }),
      step('Вращение', 'Поршни через шатуны крутят коленвал.', 'crankshaft', { duration: 5 }),
      step('Восемь передач', 'Автомат подбирает передачу, кардан передаёт момент назад.', 'transmission', { action: 'drive', duration: 6 }),
      step('Очистка', 'Катализатор у турбины очищает выхлоп.', 'catalyst', { flows: ['exhaust'], duration: 5 }),
      step('Движение', 'Задний привод толкает машину.', 'rearSusp', { shot: { pos: [4.6, 1.2, 4.8], target: [0, 0.45, 0] }, duration: 5 }),
    ],
  },
  layout: L,
}
