import type { ComponentDef, FlowDef, LearnStep, VehicleDef, WalkZone } from '../data/types'
import type { CarLayout } from '../models/carLayout'
import { carSystems, carLayers, carStart } from './common'

/*
 * Representative Toyota Fortuner diesel (second generation, AN150/AN160 body).
 * Many markets use the 2.8 L 1GD-FTV four-cylinder turbo-diesel; others use the 2.4 L 2GD-FTV.
 * Geometry is a schematic layout at real overall dimensions, not CAD.
 */
const L: CarLayout = {
  paint: '#5d646b',
  width: 1.855, wheelbase: 2.745, track: 1.545, wheelR: 0.385, tireW: 0.265,
  front: 2.3, rear: -2.49, belt: 1.24, roof: 1.8,
  profile: [[2.25, 0.52], [2.31, 0.8], [2.29, 1.02], [2.1, 1.1], [0.62, 1.22], [-0.28, 1.76], [-0.48, 1.8], [-2.28, 1.79], [-2.42, 1.68], [-2.48, 1.05], [-2.49, 0.6], [-2.4, 0.52]],
  sill: 0.52, archR: 0.47,
  window: [[0.5, 1.28], [-0.24, 1.71], [-2.24, 1.71], [-2.4, 1.6], [-2.42, 1.29]],
  windshield: [[0.64, 1.23, 0], [-0.26, 1.75, 0]],
  rearGlass: [[-2.43, 1.28, 0], [-2.33, 1.72, 0]],
  hood: { x0: 2.12, x1: 0.66, y0: 1.11, y1: 1.21 },
  tailgate: { hinge: [-2.32, 1.78, 0], to: [-2.49, 0.66, 0] },
  door: { x0: -0.72, x1: 0.42, y0: 0.55, y1: 1.24 },
  frame: true,
  engine: { x: 1.05, y: 0.85, len: 0.62, bore: 0.092, crankY: 0.66, cyl: 4 },
  turbo: [1.12, 0.9, -0.34],
  intercooler: { pos: [2.18, 0.68, 0], size: [0.06, 0.24, 0.7], label: 'air' },
  airbox: [1.72, 0.98, 0.5],
  radiator: { x: 2.05, y: 0.85, h: 0.5, w: 0.78 },
  condenser: 2.12,
  battery: [1.72, 0.92, -0.52],
  alternator: [1.42, 0.83, 0.2],
  starter: [0.72, 0.6, -0.24],
  waterPump: [1.4, 0.76, 0],
  ecu: [0.7, 1.02, 0.56],
  hpPump: [1.42, 0.96, -0.12],
  fuelFilter: [1.56, 0.74, 0.56],
  absUnit: [0.78, 0.96, -0.55],
  booster: [0.6, 1.0, 0.42],
  acCompressor: [1.38, 0.62, -0.22],
  hvac: [0.32, 0.95, 0],
  gearbox: { x0: 0.72, x1: -0.06, y: 0.62, r: 0.19 },
  transfer: [-0.18, 0.55, 0.04],
  frontDiff: [1.3725, 0.42, 0.12],
  rearDiff: [-1.3725, 0.385, 0],
  tank: { pos: [-0.72, 0.47, 0.28], size: [0.85, 0.22, 0.62] },
  exhaust: [[1.16, 0.86, -0.36], [1.1, 0.66, -0.38], [0.96, 0.44, -0.34], [0.5, 0.38, -0.31], [-0.1, 0.39, -0.34], [-1.0, 0.41, -0.36], [-1.75, 0.43, -0.38], [-2.25, 0.45, -0.46], [-2.45, 0.45, -0.55]],
  cat: { x0: 0.5, x1: 0.18 },
  dpf: { x0: 0.12, x1: -0.3 },
  muffler: { pos: [-2.0, 0.44, -0.4], len: 0.38, r: 0.11 },
  tailpipe: [-2.48, 0.45, -0.56],
  seatsFront: -0.3, seatsRear: -1.25, seatsThird: -2.0, seatY: 0.78, floorY: 0.6,
  steeringWheel: [0.2, 1.2, 0.42],
  rack: [1.25, 0.5, 0],
  pedals: [0.46, 0.84, 0.4],
  dash: 0.3,
  spare: [-2.05, 0.36, 0],
  rearAxle: 'live',
  caliper: '#c63b3b',
  lights: { head: [2.2, 1.0, 0.7], tail: [-2.46, 1.22, 0.76] },
}

const inj = [1.25, 1.1167, 0.9833, 0.85]

const flows: FlowDef[] = [
  // FUEL
  { id: 'fuel-supply', kind: 'fuel', label: 'Бак → фильтр', points: [[-0.72, 0.6, 0.45], [-0.2, 0.6, 0.5], [0.8, 0.58, 0.5], [1.4, 0.62, 0.54], [1.56, 0.7, 0.56]], speed: 0.7 },
  { id: 'fuel-lowp', kind: 'fuel', label: 'Фильтр → ТНВД', points: [[1.56, 0.82, 0.56], [1.55, 1.0, 0.3], [1.44, 1.0, -0.06]], speed: 0.8 },
  { id: 'fuel-hp', kind: 'fuel', label: 'ТНВД → Common Rail', points: [[1.42, 1.02, -0.1], [1.42, 1.07, 0.04], [1.34, 1.07, 0.1], [0.8, 1.07, 0.1]], speed: 1.6, density: 34 },
  ...inj.map((x, i) => ({ id: `fuel-inj-${i}`, kind: 'fuel' as const, label: `Форсунка ${i + 1}`, points: [[x, 1.07, 0.1], [x, 1.0, 0.02], [x, 0.91, 0]] as [number, number, number][], speed: 1.8, density: 40 })),
  { id: 'fuel-return', kind: 'fuel', label: 'Обратка в бак', points: [[0.8, 1.07, 0.1], [0.62, 1.04, 0.36], [0.4, 0.64, 0.46], [-0.4, 0.62, 0.42], [-0.6, 0.6, 0.38]], speed: 0.6, density: 10 },
  // AIR
  { id: 'air-intake', kind: 'air', label: 'Забор воздуха', points: [[2.05, 1.06, 0.55], [1.9, 1.04, 0.52], [1.82, 0.99, 0.5]] },
  { id: 'air-turbo', kind: 'air', label: 'Фильтр → компрессор', points: [[1.6, 1.0, 0.42], [1.42, 1.06, 0.1], [1.25, 1.0, -0.25], [1.15, 0.94, -0.34]] },
  { id: 'air-boost', kind: 'air', label: 'Компрессор → интеркулер', points: [[1.18, 0.95, -0.42], [1.5, 0.74, -0.58], [1.95, 0.6, -0.5], [2.18, 0.66, -0.3]], speed: 1.4 },
  { id: 'air-manifold', kind: 'air', label: 'Интеркулер → впуск', points: [[2.18, 0.7, 0.3], [1.85, 0.74, 0.5], [1.45, 0.94, 0.34], [1.3, 0.95, 0.27], [0.8, 0.95, 0.27]], speed: 1.4 },
  ...inj.map((x, i) => ({ id: `air-port-${i}`, kind: 'air' as const, label: 'Впускной канал', points: [[x, 0.95, 0.27], [x, 0.94, 0.12], [x, 0.9, 0.03]] as [number, number, number][], speed: 1.2, density: 30 })),
  { id: 'air-cabin', kind: 'air', label: 'Воздух в салон', points: [[0.32, 1.0, 0], [0.3, 1.14, 0.3], [0.0, 1.2, 0.42], [-0.6, 1.45, 0.3], [-1.6, 1.55, 0]], speed: 0.6, density: 10 },
  // EXHAUST
  ...inj.map((x, i) => ({ id: `exh-port-${i}`, kind: 'exhaust' as const, label: 'Выпускной канал', points: [[x, 0.9, -0.03], [x, 0.9, -0.15], [x, 0.9, -0.27]] as [number, number, number][], speed: 1.3, density: 30 })),
  { id: 'exh-manifold', kind: 'exhaust', label: 'Коллектор → турбина', points: [[0.84, 0.9, -0.27], [1.05, 0.9, -0.28], [1.12, 0.9, -0.3]], speed: 1.3 },
  { id: 'exh-main', kind: 'exhaust', label: 'Турбина → глушитель', points: [[1.16, 0.84, -0.36], [1.1, 0.66, -0.38], [0.96, 0.44, -0.34], [0.5, 0.38, -0.31], [-0.1, 0.39, -0.34], [-1.0, 0.41, -0.36], [-1.75, 0.43, -0.38], [-2.25, 0.45, -0.46], [-2.62, 0.45, -0.57]], speed: 1.2 },
  { id: 'exh-egr', kind: 'exhaust', label: 'EGR', points: [[0.9, 0.92, -0.25], [0.92, 1.05, -0.05], [0.95, 1.0, 0.24]], speed: 0.5, density: 12 },
  // OIL
  { id: 'oil-pump', kind: 'oil', label: 'Поддон → насос → фильтр', points: [[1.0, 0.52, 0], [1.3, 0.54, 0], [1.36, 0.62, 0.2], [1.3, 0.7, 0.22]], speed: 0.8 },
  { id: 'oil-gallery', kind: 'oil', label: 'Главная магистраль → подшипники', points: [[1.3, 0.7, 0.22], [1.05, 0.7, 0.22], [0.78, 0.7, 0.22], [0.78, 0.66, 0.05]], speed: 0.8 },
  { id: 'oil-head', kind: 'oil', label: 'К распредвалам', points: [[1.3, 0.72, 0.2], [1.32, 0.95, 0.12], [1.25, 1.0, 0.05], [0.8, 1.0, 0.05]], speed: 0.7 },
  { id: 'oil-turbo', kind: 'oil', label: 'Смазка турбины', points: [[1.25, 0.72, -0.18], [1.2, 0.84, -0.3], [1.13, 0.92, -0.34], [1.08, 0.72, -0.28], [1.0, 0.56, -0.12]], speed: 0.8, density: 22 },
  { id: 'oil-return', kind: 'oil', label: 'Слив в поддон', points: [[0.78, 0.98, -0.05], [0.76, 0.75, -0.1], [0.8, 0.56, -0.05]], speed: 0.5 },
  // COOLANT
  { id: 'cool-jacket', kind: 'coolant', label: 'Рубашка блока', points: [[1.38, 0.76, 0], [1.22, 0.8, 0.22], [0.8, 0.82, 0.22], [0.8, 0.98, 0.05], [1.36, 0.99, 0.1]], gradient: ['#3ddc97', '#ff7b54'] },
  { id: 'cool-hot', kind: 'coolant', label: 'Горячая → радиатор', points: [[1.36, 0.99, 0.1], [1.6, 1.04, 0.05], [1.9, 1.04, 0.05], [2.05, 1.06, 0.0]], gradient: ['#ff7b54', '#ff9b6b'] },
  { id: 'cool-rad', kind: 'coolant', label: 'Через радиатор', points: [[2.05, 1.06, -0.3], [2.05, 0.85, -0.32], [2.05, 0.64, -0.3]], gradient: ['#ff9b6b', '#3ddc97'] },
  { id: 'cool-return', kind: 'coolant', label: 'Холодная → помпа', points: [[2.05, 0.62, 0], [1.75, 0.6, 0], [1.42, 0.74, 0]], gradient: ['#3ddc97', '#3ddc97'] },
  { id: 'cool-heater', kind: 'coolant', label: 'Печка салона', points: [[0.8, 0.98, 0.05], [0.56, 0.98, 0.1], [0.34, 0.95, 0.05], [0.56, 0.8, -0.1], [1.36, 0.76, -0.05]], gradient: ['#ff7b54', '#3ddc97'], speed: 0.6 },
  // ELECTRIC
  { id: 'elec-starter', kind: 'electric', label: 'АКБ → стартер', points: [[1.72, 1.03, -0.52], [1.3, 0.75, -0.46], [0.9, 0.62, -0.34], [0.74, 0.6, -0.24]], speed: 2.2 },
  { id: 'elec-charge', kind: 'electric', label: 'Генератор → АКБ', points: [[1.42, 0.83, 0.28], [1.6, 0.98, 0.0], [1.72, 1.03, -0.45]], speed: 1.8 },
  { id: 'elec-ecu', kind: 'electric', label: 'АКБ → блоки управления', points: [[1.72, 1.03, -0.52], [1.3, 1.1, 0.2], [0.72, 1.04, 0.56], [0.32, 1.12, 0.42], [0.27, 1.2, 0.42]], speed: 1.8 },
  { id: 'elec-inj', kind: 'electric', label: 'ЭБУ → форсунки', points: [[0.72, 1.04, 0.56], [0.78, 1.18, 0.25], [1.25, 1.2, 0.18]], speed: 2 },
  { id: 'elec-lights', kind: 'electric', label: 'Фары', points: [[1.72, 1.03, -0.52], [2.0, 1.02, -0.6], [2.18, 1.0, -0.7]], speed: 1.8 },
  { id: 'elec-lights2', kind: 'electric', label: 'Фары', points: [[1.72, 1.03, -0.52], [1.9, 1.06, 0.1], [2.18, 1.0, 0.7]], speed: 1.8 },
  { id: 'elec-rear', kind: 'electric', label: 'Задние фонари', points: [[0.32, 1.12, 0.42], [-0.5, 0.62, 0.72], [-1.8, 0.66, 0.74], [-2.44, 1.2, 0.76]], speed: 1.8 },
  { id: 'elec-info', kind: 'electric', label: 'Мультимедиа', points: [[0.32, 1.12, 0.42], [0.3, 1.25, 0.0]], speed: 1.8 },
  // HYDRAULIC (brake fluid)
  { id: 'brake-master', kind: 'hydraulic', label: 'Главный цилиндр → ABS', points: [[0.74, 1.05, 0.42], [0.78, 1.08, 0.0], [0.78, 0.98, -0.5]], speed: 1.4 },
  { id: 'brake-fr', kind: 'hydraulic', label: 'ABS → переднее правое', points: [[0.82, 0.92, -0.58], [1.2, 0.62, -0.62], [1.42, 0.55, -0.68]], speed: 1.4 },
  { id: 'brake-fl', kind: 'hydraulic', label: 'ABS → переднее левое', points: [[0.8, 0.92, -0.48], [0.95, 0.7, 0.0], [1.2, 0.62, 0.6], [1.42, 0.55, 0.68]], speed: 1.4 },
  { id: 'brake-rear', kind: 'hydraulic', label: 'ABS → задний мост', points: [[0.74, 0.92, -0.58], [0.4, 0.5, -0.48], [-0.6, 0.52, -0.46], [-1.2, 0.55, -0.3], [-1.3, 0.55, 0]], speed: 1.4 },
  { id: 'brake-rr', kind: 'hydraulic', label: 'Задние', points: [[-1.3, 0.55, 0], [-1.33, 0.55, -0.4], [-1.33, 0.55, -0.68]], speed: 1.4 },
  { id: 'brake-rl', kind: 'hydraulic', label: 'Задние', points: [[-1.3, 0.55, 0], [-1.33, 0.55, 0.4], [-1.33, 0.55, 0.68]], speed: 1.4 },
  // A/C
  { id: 'ac-loop', kind: 'refrigerant', label: 'Компрессор → конденсатор', points: [[1.38, 0.62, -0.3], [1.8, 0.6, -0.4], [2.12, 0.7, -0.3], [2.12, 0.95, 0.2]], speed: 0.9 },
  { id: 'ac-loop2', kind: 'refrigerant', label: 'Конденсатор → испаритель', points: [[2.12, 0.98, 0.3], [1.7, 1.06, 0.4], [0.7, 1.08, 0.1], [0.36, 0.98, 0.1]], speed: 0.9 },
  { id: 'ac-loop3', kind: 'refrigerant', label: 'Испаритель → компрессор', points: [[0.36, 0.9, -0.1], [0.7, 0.75, -0.3], [1.3, 0.62, -0.3]], speed: 0.9 },
]

const C = (c: ComponentDef) => c
const shotAt = (x: number, y: number, z: number, d = 1.6): ComponentDef['shot'] => ({ pos: [x + d * 0.9, y + d * 0.55, z + d * 1.1], target: [x, y, z] })

export const components: ComponentDef[] = [
  // ENGINE
  C({ id: 'engine', name: 'Engine', ru: 'Двигатель', system: 'engine', pos: [1.05, 1.08, 0], hotspot: true, lab: 'cylinder', flows: ['fuel', 'air', 'exhaust'],
    beginner: 'Двигатель сжигает дизель и превращает энергию топлива во вращение коленвала. Всё остальное в машине получает энергию отсюда.',
    engineer: 'Рядная «четвёрка» с турбонаддувом и непосредственным впрыском Common Rail. Блок расположен продольно, за передней осью, крутящий момент уходит назад в АКПП.',
    varies: 'В разных странах: 2.8 L (1GD-FTV) или 2.4 L (2GD-FTV).', keywords: ['мотор', 'engine', 'двигатель', 'diesel'], shot: { pos: [2.55, 1.85, 1.35], target: [1.05, 0.8, 0], via: [3.8, 2.4, 1.2] } }),
  C({ id: 'cylinders', name: 'Cylinders', ru: 'Цилиндры', system: 'engine', pos: [1.05, 0.86, 0.2], lab: 'cylinder', flows: ['fuel', 'air'],
    beginner: 'Четыре «стакана», в которых ходят поршни. Именно внутри них сгорает топливо.', engineer: 'Каждый цилиндр проходит 4 такта за 2 оборота коленвала. Порядок работы 1-3-4-2: рабочий ход приходится на каждые 180°.', keywords: ['cylinder', 'цилиндр'], shot: { pos: [1.8, 1.1, 1.15], target: [1.05, 0.84, 0] } }),
  C({ id: 'pistons', name: 'Pistons', ru: 'Поршни', system: 'engine', pos: [1.02, 0.84, -0.05], lab: 'cylinder',
    beginner: 'Давление горящих газов толкает поршень вниз. Это главное движение во всём двигателе.', engineer: 'Поршни дизеля массивнее бензиновых: давление сгорания доходит до ~180–200 бар. Камера сгорания выполнена в днище поршня.', keywords: ['piston', 'поршень'], shot: { pos: [1.7, 0.92, 1.05], target: [1.02, 0.8, 0] } }),
  C({ id: 'connectingRods', name: 'Connecting rods', ru: 'Шатуны', system: 'engine', pos: [1.1, 0.74, 0], lab: 'cylinder',
    beginner: 'Шатун соединяет поршень с коленвалом и превращает движение вверх-вниз во вращение.', engineer: 'Шатун работает на сжатие в рабочем ходе и на растяжение при выпуске; кривошипно-шатунный механизм преобразует силу в момент.', keywords: ['rod', 'шатун'], shot: { pos: [1.75, 0.72, 1.05], target: [1.08, 0.72, 0] } }),
  C({ id: 'crankshaft', name: 'Crankshaft', ru: 'Коленчатый вал', system: 'engine', pos: [1.05, 0.62, 0.05], lab: 'cylinder',
    beginner: 'Коленвал вращается, когда поршни толкают его через шатуны. Его вращение и уходит к колёсам.', engineer: 'Колена смещены на 180°: цилиндры 1 и 4 движутся вместе, 2 и 3 — в противофазе. Маховик сзади сглаживает рывки между вспышками.', keywords: ['crank', 'коленвал'], shot: { pos: [1.85, 0.5, 1.15], target: [1.05, 0.64, 0] } }),
  C({ id: 'cylinderHead', name: 'Cylinder head', ru: 'Головка блока', system: 'engine', pos: [1.05, 1.02, 0.15],
    beginner: 'Крышка над цилиндрами. В ней клапаны, которые впускают воздух и выпускают газы.', engineer: 'Алюминиевая ГБЦ с двумя распредвалами (DOHC) и 4 клапанами на цилиндр. Форсунки стоят вертикально по центру камеры.', keywords: ['head', 'клапаны', 'valves', 'гбц'], shot: shotAt(1.05, 1.0, 0, 0.9) }),
  C({ id: 'camshaft', name: 'Camshafts', ru: 'Распредвалы', system: 'engine', pos: [0.9, 1.0, 0.05],
    beginner: 'Валы с кулачками открывают клапаны в нужный момент. Вращаются вдвое медленнее коленвала.', engineer: 'Привод цепью/шестернями от коленвала, передаточное отношение 2:1, так как каждый клапан открывается раз за 720°.', keywords: ['cam', 'распредвал'], shot: shotAt(0.9, 1.0, 0, 0.8) }),
  C({ id: 'turbo', name: 'Turbocharger', ru: 'Турбокомпрессор', system: 'engine', pos: [1.12, 0.9, -0.34], hotspot: true, lab: 'turbo', flows: ['air', 'exhaust', 'oil'], path: ['air-turbo', 'air-boost', 'exh-manifold', 'exh-main', 'oil-turbo'],
    beginner: 'Турбина использует энергию выхлопа, чтобы закачать в двигатель больше воздуха. Больше воздуха — можно сжечь больше топлива.', engineer: 'Турбина с изменяемой геометрией (VNT): подвижные лопатки меняют скорость потока выхлопа на колесе, поэтому наддув появляется уже на низких оборотах.', keywords: ['turbo', 'турбина', 'турбо', 'наддув', 'where is the turbo'], shot: { pos: [1.85, 1.3, -1.35], target: [1.12, 0.88, -0.34] } }),
  C({ id: 'intercooler', name: 'Intercooler', ru: 'Интеркулер', system: 'engine', pos: [2.18, 0.7, 0.2], flows: ['air'], path: ['air-boost', 'air-manifold'],
    beginner: 'Радиатор для воздуха. После турбины воздух горячий, а холодный воздух плотнее, в него помещается больше кислорода.', engineer: 'Воздухо-воздушный охладитель наддувочного воздуха; снижение температуры заряда повышает плотность и уменьшает образование NOx.', keywords: ['intercooler', 'интеркулер'], shot: shotAt(2.18, 0.7, 0, 1.3) }),
  C({ id: 'airFilter', name: 'Air filter', ru: 'Воздушный фильтр', system: 'engine', pos: [1.72, 1.06, 0.5], flows: ['air'], path: ['air-intake', 'air-turbo'],
    beginner: 'Задерживает пыль, прежде чем воздух попадёт в двигатель.', engineer: 'Бумажный фильтрующий элемент; сопротивление впуска контролирует ЭБУ через датчик расхода воздуха (MAF).', keywords: ['air filter', 'фильтр воздуха'], shot: shotAt(1.72, 1.0, 0.5, 1.0) }),
  C({ id: 'oilPan', name: 'Oil pan', ru: 'Масляный поддон', system: 'engine', pos: [1.05, 0.52, 0.18], flows: ['oil'],
    beginner: 'Резервуар для масла внизу двигателя. Отсюда масло забирает насос.', engineer: 'Мокрый картер; маслоприёмник с сеткой, насос подаёт масло через фильтр в главную магистраль.', keywords: ['oil', 'масло', 'поддон'], shot: shotAt(1.05, 0.52, 0, 1.0) }),
  C({ id: 'oilPump', name: 'Oil pump', ru: 'Масляный насос', system: 'engine', pos: [1.32, 0.56, 0.05], flows: ['oil'], path: ['oil-pump', 'oil-gallery', 'oil-head', 'oil-turbo', 'oil-return'],
    beginner: 'Гонит масло ко всем трущимся деталям. Без масла двигатель разрушится за минуты.', engineer: 'Шестерёнчатый насос с редукционным клапаном. Масло смазывает коренные и шатунные вкладыши, распредвалы, подшипник турбины и охлаждает поршни форсунками снизу.', keywords: ['oil pump', 'смазка', 'масляный насос'], shot: shotAt(1.3, 0.6, 0, 1.0) }),
  // FUEL
  C({ id: 'fuelTank', name: 'Fuel tank', ru: 'Топливный бак', system: 'fuel', pos: [-0.72, 0.6, 0.28], hotspot: true, flows: ['fuel'], path: ['fuel-supply', 'fuel-return'],
    beginner: 'Здесь хранится дизель. Бак спрятан под полом, между лонжеронами рамы.', engineer: 'Стальной бак между лонжеронами рамы под вторым рядом. В бак возвращается излишек топлива от ТНВД и форсунок.', varies: 'Объём бака зависит от рынка.', keywords: ['tank', 'бак', 'fuel tank'], shot: { pos: [-0.2, 0.25, 2.6], target: [-0.72, 0.45, 0.28] } }),
  C({ id: 'feedPump', name: 'Fuel pump', ru: 'Подкачивающий насос', system: 'fuel', pos: [-0.5, 0.52, 0.28], flows: ['fuel'], path: ['fuel-supply'],
    beginner: 'Подаёт топливо из бака к двигателю под небольшим давлением.', engineer: 'Подкачка низкого давления: электрический насос в баке или шестерёнчатый насос, встроенный в ТНВД. Он лишь питает ТНВД, высокое давление создаётся дальше.', varies: 'Расположение подкачивающего насоса зависит от версии.', keywords: ['fuel pump', 'насос'], shot: shotAt(-0.5, 0.5, 0.28, 1.2) }),
  C({ id: 'fuelFilter', name: 'Fuel filter', ru: 'Топливный фильтр', system: 'fuel', pos: [1.56, 0.82, 0.56], flows: ['fuel'], path: ['fuel-supply', 'fuel-lowp'],
    beginner: 'Очищает дизель от грязи и воды до того, как он попадёт в насос высокого давления.', engineer: 'Фильтр-сепаратор: тонкая очистка и отделение воды. Вода опасна для прецизионных пар ТНВД, которые смазываются самим топливом. Датчик воды выводит предупреждение.', keywords: ['filter', 'фильтр', 'water'], shot: shotAt(1.56, 0.78, 0.56, 0.9) }),
  C({ id: 'hpPump', name: 'High-pressure pump', ru: 'ТНВД', system: 'fuel', pos: [1.42, 1.0, -0.12], flows: ['fuel'], path: ['fuel-lowp', 'fuel-hp'],
    gauge: { label: 'Давление на выходе', value: 2200, max: 2500, unit: 'бар', note: 'до ~2000–2500 бар у современных Common Rail' },
    beginner: 'Насос, который сжимает дизель до огромного давления. Чем выше давление, тем мельче капли и тем лучше топливо сгорает.', engineer: 'Плунжерный насос с приводом от двигателя; клапан дозирования на входе управляет подачей, а датчик давления в рампе замыкает контур регулирования.', keywords: ['pump', 'тнвд', 'high pressure', 'насос высокого давления'], shot: shotAt(1.42, 0.98, -0.12, 0.8) }),
  C({ id: 'commonRail', name: 'Common Rail', ru: 'Топливная рампа', system: 'fuel', pos: [1.05, 1.1, 0.1], hotspot: true, flows: ['fuel'], path: ['fuel-hp', 'fuel-inj-0', 'fuel-inj-1', 'fuel-inj-2', 'fuel-inj-3', 'fuel-return'],
    gauge: { label: 'Давление в рампе', value: 2000, max: 2500, unit: 'бар', note: 'Холостой ход: несколько сотен бар; полная нагрузка: около 2000 бар и выше' },
    beginner: 'Общая труба с топливом под высоким давлением. Она хранит дизель и раздаёт его всем форсункам сразу.', engineer: 'Аккумулятор давления: развязывает генерацию давления (ТНВД) и дозирование (форсунки). Это позволяет делать несколько впрысков за цикл при любых оборотах.', keywords: ['common rail', 'рампа', 'rail'], shot: { pos: [1.55, 1.55, 0.95], target: [1.05, 1.1, 0.08] } }),
  C({ id: 'injectors', name: 'Injectors', ru: 'Форсунки', system: 'fuel', pos: [1.16, 1.08, 0.02], flows: ['fuel'], path: ['fuel-inj-0', 'fuel-inj-1', 'fuel-inj-2', 'fuel-inj-3'], lab: 'cylinder',
    beginner: 'Форсунка распыляет топливо прямо в цилиндр мельчайшим туманом в нужный момент.', engineer: 'Электрически управляемые форсунки делают пилотный, основной и дополнительные впрыски. Время открытия — доли миллисекунды.', keywords: ['injector', 'форсунка', 'впрыск'], shot: shotAt(1.16, 1.05, 0.05, 0.6) }),
  // EXHAUST
  C({ id: 'exhaustManifold', name: 'Exhaust manifold', ru: 'Выпускной коллектор', system: 'exhaust', pos: [0.9, 0.92, -0.3], flows: ['exhaust'], path: ['exh-port-0', 'exh-port-1', 'exh-port-2', 'exh-port-3', 'exh-manifold'],
    beginner: 'Собирает горячие газы из всех цилиндров и направляет их в турбину.', engineer: 'Чугунный коллектор, работающий при высоких температурах; короткий путь до турбины сохраняет энергию импульсов.', keywords: ['manifold', 'коллектор'], shot: shotAt(0.95, 0.9, -0.3, 0.9) }),
  C({ id: 'egr', name: 'EGR', ru: 'Рециркуляция газов', system: 'exhaust', pos: [0.93, 1.05, -0.05], flows: ['exhaust', 'air'], path: ['exh-egr'],
    beginner: 'Часть выхлопа возвращается во впуск. Пламя становится холоднее, и вредных оксидов азота образуется меньше.', engineer: 'Охлаждаемый клапан EGR дозирует инертный газ во впуск: снижает пиковую температуру сгорания и выбросы NOx.', varies: 'Конфигурация зависит от экологического класса и рынка.', keywords: ['egr', 'рециркуляция'], shot: shotAt(0.93, 1.0, 0, 0.8) }),
  C({ id: 'aftertreatment', name: 'Aftertreatment (DOC / DPF)', ru: 'Нейтрализатор и сажевый фильтр', system: 'exhaust', pos: [0.1, 0.4, -0.34], hotspot: true, flows: ['exhaust'], path: ['exh-main'],
    beginner: 'Здесь выхлоп очищается: катализатор дожигает вредные газы, а сажевый фильтр ловит частицы сажи.', engineer: 'DOC окисляет CO и HC; DPF задерживает сажу и периодически регенерируется, когда ЭБУ повышает температуру выхлопа. Системы SCR/AdBlue на части рынков нет.', varies: 'Состав системы (DOC, DPF, SCR/AdBlue) зависит от рынка и года выпуска.', keywords: ['dpf', 'doc', 'scr', 'adblue', 'сажевый', 'катализатор'], shot: { pos: [0.6, 0.0, -1.9], target: [0.1, 0.4, -0.34] } }),
  C({ id: 'muffler', name: 'Muffler', ru: 'Глушитель', system: 'exhaust', pos: [-2.0, 0.44, -0.4], flows: ['exhaust'], path: ['exh-main'],
    beginner: 'Гасит шум выхлопа, после него газы выходят наружу через выхлопную трубу.', engineer: 'Камеры и перфорированные трубы гасят звуковые волны отражением и поглощением.', keywords: ['muffler', 'глушитель', 'tailpipe'], shot: shotAt(-2.0, 0.44, -0.4, 1.1) }),
  // TRANSMISSION
  C({ id: 'transmission', name: 'Automatic transmission', ru: 'Коробка передач', system: 'transmission', pos: [0.35, 0.72, 0.2], hotspot: true, lab: 'transmission', flows: [],
    beginner: 'Коробка выбирает передачу: на низкой машина легко трогается, на высокой едет быстро и экономно.', engineer: 'Гидромеханический автомат на планетарных рядах; передачи включаются фрикционами и тормозами под давлением масла.', varies: 'В зависимости от рынка: автомат или механика, 6 ступеней у распространённых версий.', keywords: ['gearbox', 'коробка', 'transmission', 'акпп'], shot: { pos: [0.9, 1.4, 1.6], target: [0.33, 0.62, 0] } }),
  C({ id: 'torqueConverter', name: 'Torque converter', ru: 'Гидротрансформатор', system: 'transmission', pos: [0.65, 0.62, 0.2], lab: 'transmission',
    beginner: 'Передаёт вращение через масло, поэтому машина может стоять на месте с работающим мотором на передаче.', engineer: 'Насосное и турбинное колёса с реактором увеличивают момент при трогании; блокировочная муфта убирает проскальзывание на ходу.', keywords: ['torque converter', 'гидротрансформатор'], shot: shotAt(0.65, 0.62, 0, 0.8) }),
  C({ id: 'transferCase', name: 'Transfer case', ru: 'Раздаточная коробка', system: 'transmission', pos: [-0.18, 0.6, 0.04], lab: 'transmission',
    beginner: 'Делит вращение между передними и задними колёсами и даёт пониженную передачу для бездорожья.', engineer: 'Раздатка с понижающим рядом (L4). Режим работы — подключаемый 2H/4H/4L или постоянный полный привод с блокировкой — зависит от версии.', varies: 'Тип полного привода зависит от рынка.', keywords: ['transfer', 'раздатка', '4wd', 'полный привод', 'awd'], shot: shotAt(-0.18, 0.55, 0, 1.0) }),
  C({ id: 'driveshaft', name: 'Driveshafts', ru: 'Карданные валы', system: 'transmission', pos: [-0.75, 0.48, 0.0],
    beginner: 'Длинные вращающиеся валы передают мощность от коробки к мостам.', engineer: 'Задний и передний карданы с шарнирами равных угловых скоростей / крестовинами компенсируют ход подвески.', keywords: ['driveshaft', 'кардан'], shot: shotAt(-0.75, 0.45, 0, 1.4) }),
  C({ id: 'rearDiff', name: 'Rear differential', ru: 'Задний дифференциал', system: 'transmission', pos: [-1.37, 0.4, 0], lab: 'transmission',
    beginner: 'Поворачивает вращение на 90° к колёсам и позволяет им крутиться с разной скоростью в повороте.', engineer: 'Гипоидная главная передача + симметричный дифференциал; на части версий есть блокировка заднего дифференциала.', varies: 'Блокировка дифференциала есть не во всех версиях.', keywords: ['differential', 'дифференциал', 'мост'], shot: { pos: [-2.6, 0.55, 1.4], target: [-1.37, 0.4, 0] } }),
  C({ id: 'frontDiff', name: 'Front differential', ru: 'Передний дифференциал', system: 'transmission', pos: [1.37, 0.44, 0.12],
    beginner: 'Передаёт вращение передним колёсам, когда включён полный привод.', engineer: 'Передний редуктор с полуосями и ШРУСами; работает только в режимах полного привода.', keywords: ['front diff'], shot: shotAt(1.37, 0.42, 0.12, 1.0) }),
  // COOLING
  C({ id: 'radiator', name: 'Radiator', ru: 'Радиатор', system: 'cooling', pos: [2.05, 1.08, 0.25], hotspot: true, flows: ['coolant'], path: ['cool-jacket', 'cool-hot', 'cool-rad', 'cool-return'],
    beginner: 'Охлаждает горячую жидкость встречным воздухом. Жидкость приходит горячей сверху и уходит холодной снизу.', engineer: 'Алюминиевый радиатор с трубками и ламелями; рабочая температура жидкости около 85–105 °C при давлении в системе ~1 бар.', keywords: ['radiator', 'радиатор', 'cooling', 'охлаждение'], shot: { pos: [3.4, 1.3, 1.1], target: [2.05, 0.85, 0] } }),
  C({ id: 'waterPump', name: 'Water pump', ru: 'Помпа', system: 'cooling', pos: [1.42, 0.76, 0.06], flows: ['coolant'], path: ['cool-return', 'cool-jacket'],
    beginner: 'Насос, который гоняет охлаждающую жидкость по кругу.', engineer: 'Центробежная помпа с приводом от ремня/шестерён; производительность растёт с оборотами.', keywords: ['water pump', 'помпа'], shot: shotAt(1.42, 0.76, 0, 0.8) }),
  C({ id: 'thermostat', name: 'Thermostat', ru: 'Термостат', system: 'cooling', pos: [1.33, 1.0, 0.13], flows: ['coolant'],
    beginner: 'Клапан, который не пускает жидкость в радиатор, пока двигатель холодный. Так мотор быстрее прогревается.', engineer: 'Восковой термостат открывает большой круг циркуляции при ~82–88 °C.', keywords: ['thermostat', 'термостат'], shot: shotAt(1.33, 1.0, 0.12, 0.7) }),
  C({ id: 'radiatorFan', name: 'Radiator fan', ru: 'Вентилятор', system: 'cooling', pos: [1.96, 0.85, -0.25],
    beginner: 'Протягивает воздух через радиатор, когда машина стоит или едет медленно.', engineer: 'Вентилятор с вискомуфтой или электроприводом; включается по температуре.', keywords: ['fan', 'вентилятор'], shot: shotAt(1.96, 0.85, 0, 1.0) }),
  // ELECTRICAL
  C({ id: 'battery', name: 'Battery', ru: 'Аккумулятор', system: 'electrical', pos: [1.72, 1.06, -0.52], hotspot: true, flows: ['electric'], path: ['elec-starter', 'elec-charge', 'elec-ecu'],
    beginner: 'Запас электричества 12 В. Главная работа — провернуть стартер при пуске.', engineer: 'Свинцово-кислотная батарея 12 В; дизелю нужен большой пусковой ток из-за высокой компрессии.', keywords: ['battery', 'аккумулятор', 'акб', '12v'], shot: shotAt(1.72, 1.0, -0.52, 1.0) }),
  C({ id: 'starter', name: 'Starter', ru: 'Стартер', system: 'electrical', pos: [0.72, 0.62, -0.26], flows: ['electric'], path: ['elec-starter'], action: 'engineStart',
    beginner: 'Электромотор, который раскручивает двигатель при пуске, пока он не заработает сам.', engineer: 'Стартер с редуктором входит в зацепление с венцом маховика, потребляя сотни ампер на время прокрутки.', keywords: ['starter', 'стартер', 'запуск'], shot: shotAt(0.72, 0.6, -0.26, 0.9) }),
  C({ id: 'alternator', name: 'Alternator', ru: 'Генератор', system: 'electrical', pos: [1.42, 0.9, 0.22], flows: ['electric'], path: ['elec-charge'],
    beginner: 'Когда двигатель работает, генератор вырабатывает электричество для всей машины и заряжает аккумулятор.', engineer: 'Генератор переменного тока с выпрямителем и регулятором напряжения ~14 В; привод ремнём от коленвала.', keywords: ['alternator', 'генератор'], shot: shotAt(1.42, 0.85, 0.2, 0.8) }),
  C({ id: 'ecu', name: 'Engine ECU', ru: 'Блок управления', system: 'electrical', pos: [0.7, 1.06, 0.56], flows: ['electric'], path: ['elec-ecu', 'elec-inj'],
    beginner: '«Мозг» двигателя. Читает датчики и решает, когда и сколько топлива впрыснуть.', engineer: 'ECU управляет давлением в рампе, временем и количеством впрысков, наддувом (VNT), EGR и регенерацией DPF по картам и обратной связи датчиков.', keywords: ['ecu', 'эбу', 'компьютер', 'блок управления'], shot: shotAt(0.7, 1.04, 0.56, 0.8) }),
  C({ id: 'lights', name: 'Lights', ru: 'Фары и фонари', system: 'electrical', pos: [2.2, 1.06, 0.7], flows: ['electric'], path: ['elec-lights', 'elec-lights2', 'elec-rear'],
    beginner: 'Свет питается от бортовой сети 12 В. При заглушенном двигателе — от аккумулятора.', engineer: 'Светотехника на светодиодах/лампах через блок предохранителей и реле; управление — кузовной блок по шине CAN.', keywords: ['lights', 'фары'], shot: shotAt(2.2, 1.0, 0.7, 1.2) }),
  // BRAKES
  C({ id: 'brakes', name: 'Brakes', ru: 'Тормоза', system: 'brakes', pos: [1.48, 0.62, 0.72], hotspot: true, lab: 'brakes', flows: ['hydraulic'], path: ['brake-master', 'brake-fr', 'brake-fl', 'brake-rear', 'brake-rr', 'brake-rl'], action: 'brake',
    beginner: 'Тормозные колодки сжимают вращающийся диск, и трение превращает скорость машины в тепло.', engineer: 'Гидравлический двухконтурный привод с вакуумным усилителем. Спереди вентилируемые диски.', varies: 'Задние тормоза: дисковые или барабанные, зависит от версии.', keywords: ['brake', 'тормоз', 'тормоза'], shot: { pos: [2.4, 0.75, 1.75], target: [1.37, 0.4, 0.75] } }),
  C({ id: 'masterCylinder', name: 'Master cylinder', ru: 'Главный тормозной цилиндр', system: 'brakes', pos: [0.74, 1.08, 0.42], flows: ['hydraulic'], path: ['brake-master'], lab: 'brakes',
    beginner: 'Педаль толкает поршень, и он выдавливает тормозную жидкость к колёсам.', engineer: 'Тандемный цилиндр создаёт давление в двух независимых контурах; вакуумный усилитель многократно увеличивает усилие ноги.', keywords: ['master cylinder', 'главный цилиндр'], shot: shotAt(0.7, 1.0, 0.42, 0.8) }),
  C({ id: 'absUnit', name: 'ABS / VSC unit', ru: 'Блок ABS', system: 'brakes', pos: [0.78, 1.04, -0.55], flows: ['hydraulic'], path: ['brake-master', 'brake-fr', 'brake-fl', 'brake-rear'], lab: 'brakes',
    beginner: 'Если колесо начинает блокироваться, блок ABS на мгновение сбрасывает давление, и колесо снова крутится. Так машина остаётся управляемой.', engineer: 'Гидромодулятор с клапанами и насосом; по датчикам скорости колёс регулирует давление до ~15 раз в секунду. Тот же блок работает для стабилизации (VSC) и TRC.', keywords: ['abs', 'esp', 'vsc', 'антиблокировочная'], shot: shotAt(0.78, 0.96, -0.55, 0.8) }),
  // STEERING
  C({ id: 'steeringWheel', name: 'Steering wheel', ru: 'Руль', system: 'steering', pos: [0.2, 1.3, 0.42], action: 'steer',
    beginner: 'Поворачивая руль, вы крутите вал, который сдвигает рейку и поворачивает передние колёса.', engineer: 'Рулевой вал с карданами передаёт вращение на шестерню рейки; угол поворота колёс ограничен рычагами.', keywords: ['steering', 'руль'], shot: { pos: [-0.18, 1.36, 0.42], target: [0.4, 1.14, 0.42], via: [-0.1, 1.3, 1.8] } }),
  C({ id: 'steeringRack', name: 'Steering rack', ru: 'Рулевая рейка', system: 'steering', pos: [1.25, 0.56, 0.3], action: 'steer',
    beginner: 'Рейка двигается влево-вправо и через тяги поворачивает колёса.', engineer: 'Реечный механизм с гидроусилителем: насос от двигателя создаёт давление, помогая повернуть тяжёлые колёса.', varies: 'Тип усилителя руля зависит от поколения и рынка.', keywords: ['rack', 'рейка', 'усилитель'], shot: { pos: [2.1, 0.7, 1.3], target: [1.25, 0.5, 0] } }),
  // SUSPENSION
  C({ id: 'frame', name: 'Ladder frame', ru: 'Лестничная рама', system: 'suspension', pos: [-0.2, 0.52, 0.44],
    beginner: 'Прочная стальная «лестница», к которой крепятся двигатель, мосты и кузов. Классика для внедорожников.', engineer: 'Рамная конструкция (body-on-frame): кузов на резиновых опорах; рама воспринимает нагрузки бездорожья и буксировки.', keywords: ['frame', 'рама', 'chassis'], shot: { pos: [0.5, 0.2, 2.6], target: [-0.2, 0.5, 0] } }),
  C({ id: 'frontSusp', name: 'Front suspension', ru: 'Передняя подвеска', system: 'suspension', pos: [1.37, 0.72, -0.6], action: 'drive',
    beginner: 'Пружины и амортизаторы позволяют колёсам ходить вверх-вниз по неровностям, а кузов при этом остаётся спокойным.', engineer: 'Независимая на двух поперечных рычагах с коиловерами и стабилизатором.', keywords: ['suspension', 'подвеска', 'амортизатор', 'пружина'], shot: { pos: [2.3, 0.8, -1.7], target: [1.37, 0.55, -0.6] } }),
  C({ id: 'rearAxle', name: 'Rear axle', ru: 'Задний мост', system: 'suspension', pos: [-1.37, 0.6, 0.48], action: 'drive',
    beginner: 'Неразрезной мост: оба задних колеса на одной прочной балке. Очень надёжно на бездорожье.', engineer: 'Ведущий мост на четырёх продольных рычагах с тягой Панара и цилиндрическими пружинами.', keywords: ['rear axle', 'мост'], shot: { pos: [-2.9, 0.7, 1.7], target: [-1.37, 0.45, 0] } }),
  // CABIN
  C({ id: 'dashboard', name: 'Dashboard', ru: 'Приборная панель', system: 'cabin', pos: [0.4, 1.3, 0.0],
    beginner: 'Здесь приборы, экран, кнопки климата и подушка безопасности пассажира.', engineer: 'Внутри панели — блок климата (HVAC), каркас рулевой колонки, проводка и блоки управления.', keywords: ['dashboard', 'панель'], shot: { pos: [-0.25, 1.38, 0.05], target: [0.5, 1.15, 0], via: [-0.1, 1.3, 1.8] } }),
  C({ id: 'cluster', name: 'Instrument cluster', ru: 'Приборы', system: 'cabin', pos: [0.27, 1.27, 0.42],
    beginner: 'Тахометр, скорость, температура и предупреждения. Сюда приходят данные от блоков управления.', engineer: 'Комбинация приборов получает данные по CAN от ЭБУ двигателя, ABS и кузовного блока.', keywords: ['cluster', 'приборы', 'спидометр'], shot: { pos: [-0.15, 1.35, 0.42], target: [0.35, 1.22, 0.42], via: [-0.1, 1.3, 1.8] } }),
  C({ id: 'infotainment', name: 'Infotainment', ru: 'Мультимедиа', system: 'cabin', pos: [0.28, 1.32, 0.0],
    beginner: 'Экран для музыки, навигации и камеры.', engineer: 'Головное устройство подключено к сети кузова; камеры и датчики парковки передают изображение и сигналы.', keywords: ['screen', 'экран', 'мультимедиа'], shot: { pos: [-0.2, 1.36, 0.12], target: [0.3, 1.27, 0], via: [-0.1, 1.3, 1.8] } }),
  C({ id: 'airbag', name: 'Airbag', ru: 'Подушка безопасности', system: 'cabin', pos: [0.12, 1.24, 0.42], action: 'airbag',
    beginner: 'При ударе подушка надувается за доли секунды и мягко ловит водителя.', engineer: 'Датчики ускорения → блок SRS → пиропатрон газогенератора: подушка раскрывается примерно за 30–50 мс.', keywords: ['airbag', 'подушка'], shot: { pos: [-0.2, 1.38, 0.62], target: [0.18, 1.2, 0.42], via: [-0.1, 1.3, 1.8] } }),
  C({ id: 'seats', name: 'Seats & belts', ru: 'Сиденья и ремни', system: 'cabin', pos: [-0.35, 1.2, -0.42],
    beginner: 'Три ряда сидений. Ремень держит человека, а преднатяжитель затягивает его при ударе.', engineer: 'Ремни с преднатяжителями и ограничителями усилия; третий ряд складывается.', keywords: ['seat', 'сиденья', 'ремни', 'belt'], shot: { pos: [-1.9, 1.5, 0.0], target: [-0.3, 1.0, 0] } }),
  C({ id: 'hvac', name: 'Air conditioning', ru: 'Кондиционер', system: 'climate', pos: [0.32, 1.06, -0.2], flows: ['refrigerant', 'air'], path: ['ac-loop', 'ac-loop2', 'ac-loop3', 'air-cabin'],
    beginner: 'Кондиционер «перекачивает» тепло: забирает его из салона и выбрасывает через радиатор спереди.', engineer: 'Компрессор сжимает хладагент → конденсатор отдаёт тепло → расширительный клапан → испаритель в салоне охлаждает воздух и осушает его.', keywords: ['ac', 'кондиционер', 'климат', 'air conditioning'], shot: shotAt(0.32, 1.0, 0, 1.1) }),
  C({ id: 'acCompressor', name: 'A/C compressor', ru: 'Компрессор кондиционера', system: 'climate', pos: [1.38, 0.68, -0.24], flows: ['refrigerant'], path: ['ac-loop', 'ac-loop2', 'ac-loop3'],
    beginner: 'Сжимает хладагент. Работает от ремня двигателя.', engineer: 'Компрессор переменной производительности с муфтой; подключается по запросу климат-контроля.', keywords: ['compressor'], shot: shotAt(1.38, 0.62, -0.24, 0.8) }),
  // TRUNK
  C({ id: 'trunk', name: 'Cargo area', ru: 'Багажник', system: 'trunk', pos: [-2.1, 1.0, 0.0], action: 'openTrunk',
    beginner: 'Позади — третий ряд сидений и багажник. Запасное колесо подвешено снаружи, под полом.', engineer: 'Третий ряд складывается к бортам; под полом — полноразмерная запаска, рядом проходит выхлопная система.', keywords: ['trunk', 'багажник', 'boot'], shot: { pos: [-3.9, 1.7, 0.8], target: [-2.0, 0.9, 0] } }),
  C({ id: 'spareWheel', name: 'Spare wheel', ru: 'Запасное колесо', system: 'trunk', pos: [-2.05, 0.42, 0.3],
    beginner: 'Полноразмерное запасное колесо висит под задней частью кузова.', engineer: 'Подвешено на лебёдке под полом; опускается тросом.', keywords: ['spare', 'запаска'], shot: { pos: [-3.2, 0.25, 1.5], target: [-2.05, 0.38, 0] } }),
]

const walk: WalkZone[] = [
  { id: 'front', label: 'FRONT', shot: { pos: [5.6, 1.5, 2.6], target: [1.4, 0.9, 0] } },
  { id: 'bay', label: 'ENGINE BAY', shot: { pos: [2.65, 2.0, 1.15], target: [1.1, 0.85, 0], via: [4.2, 2.6, 1.2] }, xray: true, open: ['hood'], focus: ['engine'] },
  { id: 'left', label: 'LEFT SIDE', shot: { pos: [0.0, 1.4, 5.8], target: [0, 0.9, 0] } },
  { id: 'door', label: 'DRIVER DOOR', shot: { pos: [-0.2, 1.35, 2.3], target: [0.1, 1.0, 0.4] }, open: ['door'] },
  { id: 'cabin', label: 'CABIN', shot: { pos: [-0.95, 1.62, 0.02], target: [0.45, 1.08, 0.3], via: [-0.4, 1.5, 1.7] }, xray: true },
  { id: 'rear', label: 'REAR SEATS', shot: { pos: [-1.95, 1.45, 0.0], target: [-0.3, 1.0, 0] }, xray: true },
  { id: 'trunk', label: 'TRUNK', shot: { pos: [-3.9, 1.65, 0.6], target: [-2.0, 0.9, 0] }, open: ['trunk'] },
  { id: 'axle', label: 'REAR AXLE', shot: { pos: [-3.0, 0.65, 1.8], target: [-1.37, 0.42, 0] }, xray: true, focus: ['suspension', 'transmission'] },
  { id: 'under', label: 'UNDERBODY', shot: { pos: [1.4, -1.6, 2.4], target: [-0.2, 0.45, 0] }, lift: true },
]

const step = (title: string, text: string, focus: string, extra: Partial<LearnStep> = {}): LearnStep => ({ title, text, focus, ...extra })

export const fortuner: VehicleDef<CarLayout> = {
  id: 'fortuner', kind: 'car', name: 'TOYOTA FORTUNER', line: 'DIESEL · SUV', type: 'Turbo-diesel · Common Rail',
  tagline: 'Рамный внедорожник с турбодизелем и полным приводом.',
  representative: 'Representative Toyota Fortuner diesel powertrain',
  varies: 'Exact configuration may vary by model year, engine and market.',
  accent: '#ff8a3d',
  specs: [
    { label: 'Engine', value: 'Inline-4 turbo-diesel' },
    { label: 'Injection', value: 'Common Rail, direct' },
    { label: 'Layout', value: 'Front, longitudinal' },
    { label: 'Drive', value: 'RWD / 4WD by version' },
    { label: 'Body', value: 'Body-on-frame SUV' },
    { label: 'Size', value: '≈ 4.8 × 1.86 × 1.84 m' },
  ],
  systems: carSystems,
  components,
  flows,
  walk,
  overview: { pos: [6.4, 2.9, 6.9], target: [0, 0.8, 0] },
  layers: carLayers,
  scale: 1,
  awd: true,
  gears: { count: 6, label: 'Representative 6-speed automatic' },
  checklist: [
    { label: 'Diesel', ids: ['engine', 'cylinders', 'injectors', 'commonRail'] },
    { label: 'Turbo', ids: ['turbo', 'intercooler'] },
    { label: 'Transmission', ids: ['transmission', 'transferCase', 'rearDiff', 'torqueConverter'] },
    { label: 'Brakes', ids: ['brakes', 'absUnit', 'masterCylinder'] },
    { label: 'Cooling', ids: ['radiator', 'waterPump', 'thermostat'] },
    { label: 'Electrical', ids: ['battery', 'alternator', 'starter', 'ecu'] },
  ],
  start: carStart(true),
  powerPath: {
    title: 'HOW DIESEL POWER REACHES THE WHEELS',
    steps: [
      step('FUEL TANK', 'Дизель хранится в баке под полом.', 'fuelTank', { flows: ['fuel'], paths: ['fuel-supply'] }),
      step('FUEL PUMP', 'Подкачивающий насос подаёт топливо к двигателю.', 'feedPump', { paths: ['fuel-supply'] }),
      step('FUEL FILTER', 'Фильтр отделяет грязь и воду.', 'fuelFilter', { paths: ['fuel-supply', 'fuel-lowp'] }),
      step('HIGH-PRESSURE PUMP', 'ТНВД сжимает дизель до ~2000 бар.', 'hpPump', { paths: ['fuel-lowp', 'fuel-hp'] }),
      step('COMMON RAIL', 'Рампа хранит топливо под давлением для всех форсунок.', 'commonRail', { paths: ['fuel-hp'] }),
      step('INJECTORS', 'Форсунки распыляют топливо в цилиндры.', 'injectors', { paths: ['fuel-inj-0', 'fuel-inj-1', 'fuel-inj-2', 'fuel-inj-3'], action: 'engineStart' }),
      step('CYLINDERS', 'Топливо попадает в раскалённый сжатый воздух.', 'cylinders', { flows: ['air', 'fuel'] }),
      step('COMBUSTION', 'Дизель воспламеняется сам — от температуры сжатия.', 'cylinders', { flows: ['fuel', 'exhaust'] }),
      step('PISTONS', 'Давление газов толкает поршни вниз.', 'pistons'),
      step('CONNECTING RODS', 'Шатуны передают силу на коленвал.', 'connectingRods'),
      step('CRANKSHAFT', 'Коленвал превращает толчки во вращение.', 'crankshaft'),
      step('TRANSMISSION', 'Коробка подбирает передаточное число.', 'transmission', { action: 'drive' }),
      step('TRANSFER CASE', 'Раздатка делит момент между мостами.', 'transferCase'),
      step('DRIVESHAFT', 'Карданы несут вращение к мостам.', 'driveshaft'),
      step('DIFFERENTIAL', 'Дифференциал поворачивает поток на 90° и делит между колёсами.', 'rearDiff'),
      step('AXLES', 'Полуоси вращают ступицы.', 'rearAxle'),
      step('WHEELS', 'Колёса толкают машину вперёд.', 'frontSusp', { shot: { pos: [3.2, 1.0, 4.4], target: [0, 0.5, 0] } }),
    ],
  },
  learn: [
    step('STEP 01', 'Топливо выходит из бака и идёт к двигателю.', 'fuelTank', { flows: ['fuel'] }),
    step('STEP 02', 'Воздух проходит через фильтр и турбину и попадает в цилиндры.', 'turbo', { flows: ['air'] }),
    step('STEP 03', 'Форсунки впрыскивают дизель под огромным давлением.', 'commonRail', { flows: ['fuel'], action: 'engineStart' }),
    step('STEP 04', 'Сгорание создаёт давление над поршнем.', 'cylinders', { flows: ['fuel', 'air'] }),
    step('STEP 05', 'Поршень движется вниз.', 'pistons'),
    step('STEP 06', 'Коленвал вращается.', 'crankshaft'),
    step('STEP 07', 'Мощность приходит в коробку передач.', 'transmission', { action: 'drive' }),
    step('STEP 08', 'Колёса вращаются, машина едет.', 'rearDiff', { shot: { pos: [4.2, 1.2, 4.6], target: [0, 0.6, 0] } }),
  ],
  demo: {
    id: 'demo-diesel', vehicle: 'fortuner', title: 'How diesel fuel becomes motion', subtitle: 'Путь дизеля от бака до колёс',
    steps: [
      step('Топливо в баке', 'Всё начинается здесь: дизель лежит в баке под вторым рядом.', 'fuelTank', { flows: ['fuel'], duration: 5 }),
      step('Очистка и давление', 'Фильтр убирает воду, а ТНВД сжимает топливо до ~2000 бар.', 'hpPump', { paths: ['fuel-supply', 'fuel-lowp', 'fuel-hp'], duration: 6 }),
      step('Запуск', 'Стартер проворачивает двигатель, ЭБУ открывает форсунки.', 'starter', { action: 'engineStart', paths: ['elec-starter'], duration: 5 }),
      step('Воздух под давлением', 'Турбина, раскрученная выхлопом, нагнетает воздух в цилиндры.', 'turbo', { flows: ['air', 'exhaust'], duration: 6 }),
      step('Вспышка без искры', 'Сжатый воздух нагревается так сильно, что дизель воспламеняется сам.', 'cylinders', { flows: ['fuel', 'air'], duration: 6 }),
      step('Вращение', 'Поршни толкают шатуны, коленвал крутится.', 'crankshaft', { duration: 5 }),
      step('К колёсам', 'Коробка, раздатка и карданы несут момент на оба моста.', 'transferCase', { action: 'drive', duration: 6 }),
      step('Выхлоп', 'Отработавшие газы чистятся в DOC/DPF и выходят сзади.', 'aftertreatment', { flows: ['exhaust'], duration: 6 }),
      step('Движение', 'Fortuner едет.', 'frontSusp', { shot: { pos: [4.6, 1.4, 4.8], target: [0, 0.6, 0] }, duration: 5 }),
    ],
  },
  layout: L,
}
